secrets: /config/appdaemon/secrets.yaml
log:
  accessfile: /config/appdaemon/access.log
  errorfile: /config/appdaemon/error.log
  logfile: /config/appdaemon/appdaemon.log
  log_generations: 2
  log_size: 2000000
appdaemon:
  app_dir: /config/appdaemon/apps
  threads: 30

  # EXTRA - common vars
  path_base_data: /config
  path_ha_conf: /config

  notifier: notify.mobile_app_iphone
  chatid_sensor: sensor.telegram_default_chatid
  bot_group: notify.telegram_group
  bot_notifier: telegram_bot.send_message

  media_player: media_player.kodi

  plugins:
    HASS:
      type: hass
      ha_url: http://hassio/homeassistant
      ha_key: !secret ha_key
      #commtype: SSE
HADashboard:
  dash_url: http://127.0.0.1:5050
  dash_dir: /config/appdaemon/dashboards

# Apps
#hello_world:
#  module: hello
#  class: HelloWorld
