homeassistant:
  customize:
    camera.pi_zero_cam_1:
      friendly_name: Sal贸n
    camera.pi_zero_cam_2:
      friendly_name: Cocina
    camera.sricam_360:
      friendly_name: Sal贸n
    camera.iegeek_hd:
      friendly_name: Estudio
    camera.kmoon_ipcam100:
      friendly_name: Terraza

    switch.motion_detection_sricam_360:
      friendly_name: VideoMov. Sal贸n
      icon: mdi:video
    switch.motion_detection_iegeek_hd:
      friendly_name: VideoMov. Estudio
      icon: mdi:video
    switch.motion_detection_kmoon_ipcam100:
      friendly_name: VideoMov. Terraza
      icon: mdi:video
    switch.motion_detection_pizerocam1:
      friendly_name: VideoMov. Sal贸n
      icon: mdi:video
    switch.motion_detection_pizerocam2:
      friendly_name: VideoMov. Cocina
      icon: mdi:video

switch:
- platform: template
  scan_interval: 60
  switches:
    motion_detection_pizerocam1:
      value_template: "{{ is_state('camera.pi_zero_cam_1', 'recording') }}"
      entity_id: camera.pi_zero_cam_1
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_1
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_1
    motion_detection_pizerocam2:
      value_template: "{{ is_state('camera.pi_zero_cam_2', 'recording') }}"
      entity_id: camera.pi_zero_cam_2
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_2
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.pi_zero_cam_2
#    motion_detection_sricam_360:
#      value_template: "{{ is_state('camera.sricam_360', 'recording') }}"
#      entity_id: camera.sricam_360
#      turn_on:
#        service: camera.enable_motion_detection
#        data:
#          entity_id: camera.sricam_360
#      turn_off:
#        service: camera.disable_motion_detection
#        data:
#          entity_id: camera.sricam_360
    motion_detection_iegeek_hd:
      value_template: "{{ is_state('camera.iegeek_hd', 'recording') }}"
      entity_id: camera.iegeek_hd
      turn_on:
        service: camera.enable_motion_detection
        data:
          entity_id: camera.iegeek_hd
      turn_off:
        service: camera.disable_motion_detection
        data:
          entity_id: camera.iegeek_hd
#    motion_detection_kmoon_ipcam100:
#      value_template: "{{ is_state('camera.kmoon_ipcam100', 'recording') }}"
#      entity_id: camera.kmoon_ipcam100
#      turn_on:
#        service: camera.enable_motion_detection
#        data:
#          entity_id: camera.kmoon_ipcam100
#      turn_off:
#        service: camera.disable_motion_detection
#        data:
#          entity_id: camera.kmoon_ipcam100

###############################################################################
# IP CAMERAS (from Motioneye
###############################################################################
camera:
  # Kitchen camera
  - platform: motioneye
    snapshot_url: !secret motioneye_rpizero2_snapshot_url
    name: Pi Zero Cam 2
    with_motion_control: true
    control_port: 7999
    camera_id: 1

  # Living room camera
  - platform: motioneye
    snapshot_url: !secret motioneye_rpizero_snapshot_url
    name: Pi Zero Cam 1
    with_motion_control: true
    control_port: 7999
    camera_id: 1

#  # Living room camera
#  - platform: motioneye
#    snapshot_url: !secret sricam_motioneye_local_snapshot
#    name: SriCAM 360
#    with_motion_control: true
#    control_port: 7999
#    camera_id: 2
#
  # Wyze cams
  - platform: generic
    name: WyzeCamPan
    still_image_url: !secret wyzecampan_meye_snapshot
#    stream_source: !secret wyzecampan_rstp_url

  # Exterior camera
  - platform: generic
    name: WyzeCam2
    still_image_url: !secret wyzecam2_meye_snapshot
#    stream_source: !secret wyzecam2_rstp_url

  # Office camera
  - platform: motioneye
    snapshot_url: !secret iegeek_motioneye_local_snapshot
    name: Escam
    with_motion_control: true
    control_port: 7999
    camera_id: 3

#  - platform: ffmpeg
#    input: !secret sricam_full_rstp
#    name: SriCAM 360
#    port: 5000
#    extra_arguments:

#  - platform: onvif
#    host: !secret sricam_lan_ip
#    name: SriCAM 360
#    username: !secret sricam_user
#    password: !secret sricam_pwd
##    port: 5000
##    extra_arguments:
