###############################################################################
# enerPI current meter
###############################################################################
homeassistant:
  customize:
    sensor.elecprice_range:
      icon: mdi:currency-eur
    sensor.esp32ener_consumption_day:
      icon: mdi:flash-outline
    sensor.esp32ener_power:
      icon: mdi:flash
      friendly_name: Consumo medido
    sensor.esp32ener_real_power:
      icon: mdi:flash
      friendly_name: Consumo real
    sensor.esp32ener_ch1:
      icon: mdi:power-plug
      friendly_name: Circuito 1 (general)
    sensor.esp32ener_ch2:
      icon: mdi:flash-circle
      friendly_name: Circuito 2 (termo,AC,domótica)
    sensor.esp32ener_ch3:
      icon: mdi:stove
      friendly_name: Cocina y horno

    binary_sensor.esp32_ener_online:
      friendly_name: Current Meter Online
    input_number.enerpi_max_power:
      friendly_name: Max (kW)
      icon: mdi:flash-red-eye
    input_number.enerpi_max_power_reset:
      friendly_name: Reset at (kW)
      icon: mdi:flash-off

input_number:
  # enerPI alarm config
  enerpi_max_power:
    initial: 5.0
    min: 2.0
    max: 6.0
    step: 0.25

  enerpi_max_power_reset:
    initial: 2.5
    min: 2.0
    max: 6.0
    step: 0.25

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp32_ener_lwt
    name: esp32_Ener Online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: template
    sensors:
      electricity_high_cost_interval:
        friendly_name: "Electricidad: Periodo punta"
        device_class: power
        value_template: >-
          {{ (utcnow().hour >= 11) and (utcnow().hour < 21) }}
        entity_id:
          - sensor.date_time


sensor:
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.mean_10s }}"
#    name: enerpi_power
#    unit_of_measurement: "W"
#    json_attributes: 'consumo_Wh,peak,mean_1m,mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.power }}"
#    name: enerpi_ch1
#    unit_of_measurement: "W"
#    json_attributes: 'ch1_mean_10s,ch1_mean_1m,ch1_mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.power2 }}"
#    name: enerpi_ch2
#    unit_of_measurement: "W"
#    json_attributes: 'ch2_mean_10s,ch2_mean_1m,ch2_mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.ldr }}"
#    name: enerpi_ldr
#    unit_of_measurement: "%"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60

#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp32_ener_stream
#    value_template: "{{ value_json.total | float | round }}"
#    name: esp32ener_power
#    unit_of_measurement: "W"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[2] | float | round }}"
#    name: esp32ener_ch3
    name: esp32ener_power
    unit_of_measurement: "W"
#    json_attributes: 'Energy_instant_Wh,Energy_hour_Wh,Energy_day_kWh,ts,delta_ms,counter,Peak_CH3,Low_CH3'
    json_attributes_topic: !secret mqtt_topic_esp32_ener_stream
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[0]  | float | round }}"
    name: esp32ener_ch1
    unit_of_measurement: "W"
#    json_attributes: 'Peak_CH1,Low_CH1,ts'
    json_attributes_topic: !secret mqtt_topic_esp32_ener_stream
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[1]  | float | round }}"
    name: esp32ener_ch2
    unit_of_measurement: "W"
#    json_attributes: 'Peak_CH2,Low_CH2,ts'
    json_attributes_topic: !secret mqtt_topic_esp32_ener_stream
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60

  - platform: template
    sensors:
      esp32ener_consumption_day:
        friendly_name: "Consumo hoy"
        unit_of_measurement: 'kWh'
        value_template: "{{ states.sensor.esp32ener_power.attributes.Energy_day_kWh | float | round(2) }}"
        entity_id: sensor.esp32ener_power
      elecprice_range:
        friendly_name: "Precio luz"
        value_template: "{% set price = 100 * (states.sensor.pvpc.state | float) %}{% if price > 15 %}Muy cara{% elif price > 12 %}Cara{% elif price > 8 %}Normal{% elif price > 4 %}Barata{% else %}Muy barata{% endif %}"
        entity_id: sensor.pvpc
#      esp32ener_real_power:
#        friendly_name: "Potencia real"
#        unit_of_measurement: 'W'
#        # -367.9333 + [ 1.79581719  1.65896788 -0.65356452] * X
#        value_template: "{{ (-367.9333 + 1.79581719 * (states.sensor.esp32ener_ch1.state | float) + 1.65896788 * (states.sensor.esp32ener_ch2.state | float) - 0.65356452 * (states.sensor.esp32ener_power.state | float ))| round(2) }}"
#        entity_id:
#          - sensor.esp32ener_ch1
#          - sensor.esp32ener_ch2
#          - sensor.esp32ener_power

  - platform: elecprice_spain_pvpc
    electric_rate: discriminacion
    timeout: 20
