###############################################################################
# enerPI current meter
###############################################################################
homeassistant:
  customize:
    # enerPI sensors:
    sensor.enerpi_power:
      icon: mdi:flash
      friendly_name: Main power
      homebridge_hidden: true
    sensor.enerpi_ch1:
      icon: mdi:power-plug
      friendly_name: Circuito 1
      homebridge_hidden: true
    sensor.enerpi_ch2:
      icon: mdi:flash-circle
      friendly_name: Circuito 2
      homebridge_hidden: true
    binary_sensor.enerpi_online:
      homebridge_hidden: true
    sensor.enerpi_ldr:
      icon: mdi:lightbulb
      friendly_name: Iluminación en cuadro
      homebridge_hidden: true
      hidden: true

    input_boolean.switch_control_enerpi_max_power:
      friendly_name: enerPI - control de potencia
      icon: mdi:toggle-switch
      homebridge_hidden: true
    input_number.enerpi_max_power:
      friendly_name: Max (kW)
      icon: mdi:flash-red-eye
      homebridge_hidden: true
    input_number.enerpi_max_power_reset:
      friendly_name: Reset at (kW)
      icon: mdi:flash-off
      homebridge_hidden: true

input_number:
  # enerPI alarm config
  enerpi_max_power:
    initial: 4.6
    min: 2.0
    max: 6.0
    step: 0.25

  enerpi_max_power_reset:
    initial: 2.5
    min: 2.0
    max: 6.0
    step: 0.25

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_enerpi_lwt
    name: enerPI Online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: template
    sensors:
      electricity_high_cost_interval:
        friendly_name: "Electricidad: Periodo punta"
        device_class: problem
        value_template: >-
          {{ (utcnow().hour >= 11) and (utcnow().hour < 21) }}

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_enerpi_status
    value_template: "{{ value_json.mean_10s }}"
    name: enerpi_power
    unit_of_measurement: "W"
    json_attributes: 'consumo_Wh,peak,mean_1m,mean_5m,counter'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_enerpi_status
    value_template: "{{ value_json.power }}"
    name: enerpi_ch1
    unit_of_measurement: "W"
    json_attributes: 'ch1_mean_10s,ch1_mean_1m,ch1_mean_5m,counter'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_enerpi_status
    value_template: "{{ value_json.power2 }}"
    name: enerpi_ch2
    unit_of_measurement: "W"
    json_attributes: 'ch2_mean_10s,ch2_mean_1m,ch2_mean_5m,counter'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_enerpi_status
    value_template: "{{ value_json.ldr }}"
    name: enerpi_ldr
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60

# Grafana dashboards as generic cameras
camera:
  - platform: generic
    still_image_url: !secret grafana_db_elec_consumo_templ
    name: Consumo 7d
    username: !secret grafana_username
    password: !secret grafana_password
    limit_refetch_to_url_change: True

  - platform: generic
    still_image_url: !secret grafana_db_elec_power_templ
    name: Electricidad 24h
    username: !secret grafana_username
    password: !secret grafana_password
    limit_refetch_to_url_change: True
