###############################################################################
# enerPI current meter
###############################################################################
homeassistant:
  customize:
    # enerPI sensors:
#    sensor.enerpi_power:
#      icon: mdi:flash
#      friendly_name: Main power
#      homebridge_hidden: true
#    sensor.enerpi_ch1:
#      icon: mdi:power-plug
#      friendly_name: Circuito 1
#      homebridge_hidden: true
#    sensor.enerpi_ch2:
#      icon: mdi:flash-circle
#      friendly_name: Circuito 2
#      homebridge_hidden: true
    sensor.pvpc:
      homebridge_hidden: true
#      icon: mdi:cash
    sensor.esp32ener_consumption_day:
      icon: mdi:flash-outline
      homebridge_hidden: true
    sensor.esp32ener_power:
      icon: mdi:flash
      friendly_name: Consumo actual
      homebridge_hidden: true
    sensor.esp32ener_ch1:
      icon: mdi:power-plug
      friendly_name: Circuito 1 (general)
      homebridge_hidden: true
    sensor.esp32ener_ch2:
      icon: mdi:flash-circle
      friendly_name: Circuito 2 (termo,AC,domótica)
      homebridge_hidden: true
    sensor.esp32ener_ch3:
      icon: mdi:stove
      friendly_name: Cocina y horno
      homebridge_hidden: true

    binary_sensor.esp32_ener_online:
      homebridge_hidden: true
#    sensor.enerpi_ldr:
#      icon: mdi:lightbulb
#      friendly_name: Iluminación en cuadro
#      homebridge_hidden: true
#      hidden: true

    input_boolean.switch_control_enerpi_max_power:
      friendly_name: enerPI - control de potencia
      icon: mdi:toggle-switch
      homebridge_hidden: true
    input_number.enerpi_max_power:
      friendly_name: Max (kW)
      icon: mdi:flash-red-eye
      homebridge_hidden: true
    input_number.enerpi_max_power_reset:
      friendly_name: Reset at (kW)
      icon: mdi:flash-off
      homebridge_hidden: true

input_number:
  # enerPI alarm config
  enerpi_max_power:
#    initial: 4.75
    min: 2.0
    max: 6.0
    step: 0.25

  enerpi_max_power_reset:
#    initial: 2.5
    min: 2.0
    max: 6.0
    step: 0.25

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp32_ener_lwt
    name: esp32_Ener Online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: template
    sensors:
      electricity_high_cost_interval:
        friendly_name: "Electricidad: Periodo punta"
        device_class: power
        value_template: >-
          {{ (utcnow().hour >= 11) and (utcnow().hour < 21) }}

sensor:
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.mean_10s }}"
#    name: enerpi_power
#    unit_of_measurement: "W"
#    json_attributes: 'consumo_Wh,peak,mean_1m,mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.power }}"
#    name: enerpi_ch1
#    unit_of_measurement: "W"
#    json_attributes: 'ch1_mean_10s,ch1_mean_1m,ch1_mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.power2 }}"
#    name: enerpi_ch2
#    unit_of_measurement: "W"
#    json_attributes: 'ch2_mean_10s,ch2_mean_1m,ch2_mean_5m,counter'
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_enerpi_status
#    value_template: "{{ value_json.ldr }}"
#    name: enerpi_ldr
#    unit_of_measurement: "%"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: 60

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.total | float | round }}"
    name: esp32ener_power
    unit_of_measurement: "W"
    json_attributes: 'Energy_instant_Wh,Energy_hour_Wh,Energy_day_kWh,ts,delta_ms,counter'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[0]  | float | round }}"
    name: esp32ener_ch1
    unit_of_measurement: "W"
    json_attributes: 'Peak_CH1,Low_CH1,ts'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[1]  | float | round }}"
    name: esp32ener_ch2
    unit_of_measurement: "W"
    json_attributes: 'Peak_CH2,Low_CH2,ts'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp32_ener_stream
    value_template: "{{ value_json.rms[2] | float | round }}"
    name: esp32ener_ch3
    unit_of_measurement: "W"
    json_attributes: 'Peak_CH3,Low_CH3,ts'
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: 60

  - platform: template
    sensors:
      esp32ener_consumption_day:
        friendly_name: "Consumo hoy"
        unit_of_measurement: 'kWh'
        value_template: "{{ states.sensor.esp32ener_power.attributes.Energy_day_kWh | float | round(2) }}"

  - platform: elecprice_spain_pvpc
    electric_rate: discriminacion

# Grafana dashboards as generic cameras
camera:
  - platform: generic
    still_image_url: !secret grafana_db_elec_consumo_templ
    name: Consumo 7d
    username: !secret grafana_username
    password: !secret grafana_password
    limit_refetch_to_url_change: True

  - platform: generic
    still_image_url: !secret grafana_db_elec_power_templ
    name: Electricidad 24h
    username: !secret grafana_username
    password: !secret grafana_password
    limit_refetch_to_url_change: True
