homeassistant:
  customize:
    sensor.sensor_wine_temperature:
      friendly_name: Temperatura Vinoteca
      icon: mdi:thermometer
    sensor.sensor_wine_humidity:
      friendly_name: Humedad Vinoteca
      icon: mdi:water-percent
    sensor.sensor_wine_snum:
      friendly_name: 'Sample # (vinoteca)'
    binary_sensor.sensor_wine_online:
      friendly_name: Vinoteca Online

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_wine_lwt
    name: sensor_wine_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_wine_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% endif %}"
    name: sensor_wine_temperature
    unit_of_measurement: "°C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration_batt

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_wine_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% endif %}"
    name: sensor_wine_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration_batt

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_wine_status
    value_template: "{{ value_json.status.wake}}"
#    value_template: "{{ value_json.sample.snum}}"
    unit_of_measurement: "sample"
#    json_attributes: 'ip,bssid,rssi,wifi_ap,clientid,status,network,ts,sample'
    json_attributes_topic: !secret mqtt_topic_esp_wine_status
    name: sensor_wine_snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration_batt
