homeassistant:
  customize:
    sensor.sensor_office_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
      homebridge_name: Temperatura estudio
#      homebridge_hidden: true
    sensor.sensor_office_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
#      homebridge_hidden: true
      homebridge_name: Humedad estudio
      homebridge_sensor_type: humidity
    sensor.sensor_office_pressure:
      friendly_name: Presión
      icon: mdi:weather-cloudy
      homebridge_hidden: true
    sensor.sensor_office_illumination:
      friendly_name: Iluminación
      icon: mdi:lightbulb-on
      homebridge_hidden: true

    sensor.sensor_office__snum:
      friendly_name: 'Sample # (office)'
      homebridge_hidden: true
      
    sensor.sensor_office_adc1:
      friendly_name: 'Sensor de humos 1'
      icon: mdi:biohazard
      homebridge_hidden: true
    sensor.sensor_office_adc2:
      friendly_name: 'Sensor de humos 2'
      icon: mdi:biohazard
      homebridge_hidden: true
    
#    light.sensor_office__rgblight:
#      friendly_name: 'LED RGB Light'
#      icon: mdi:led-on
#      homebridge_hidden: true
#    #switch.sensor_office__switch_led:
#    light.sensor_office__switch_led:
#      friendly_name: 'LED en uso'
#      icon: mdi:led-outline
#      homebridge_hidden: true
    
    binary_sensor.sensor_office_mov1:
      friendly_name: 'Movimiento (office)'
      homebridge_hidden: true
#    binary_sensor.sensor_office_mov2:
#      friendly_name: 'Movimiento 2'
#      homebridge_hidden: true
    binary_sensor.sensor_office_online:
      friendly_name: Office Online
      homebridge_hidden: true


binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_office_lwt
    name: sensor_office_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: mqtt
    device_class: motion
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{{ value_json.sample.bin[0]}}"
    name: sensor_office_mov1
    qos: !secret mqtt_default_qos
    payload_on: 1
    payload_off: 0
    availability_topic: !secret mqtt_topic_esp_office_lwt
    payload_available: "online"
    payload_not_available: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% endif %}"
    name: sensor_office_temperature
    unit_of_measurement: "°C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% endif %}"
    name: sensor_office_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{% if 'pres' in value_json.sample %}{{ value_json.sample.pres | round(1) }}{% endif %}"
    name: sensor_office_pressure
    unit_of_measurement: "mb"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{% if 'lux' in value_json.sample %}{{ value_json.sample.lux}}{% endif %}"
    name: sensor_office_illumination
    unit_of_measurement: "lx"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_office_status
    value_template: "{{ value_json.sample.snum}}"
    unit_of_measurement: "sample"
    json_attributes: 'status,network,ts,sample'
    name: sensor_office__snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp_office_status
#    value_template: "{{ (value_json.sample.adc[0] / 40.95) | round(1) }}"
#    name: sensor_office_adc1
#    unit_of_measurement: "%h"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: !secret mqtt_default_expiration
#
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp_office_status
#    value_template: "{{ (value_json.sample.adc[1] / 40.95) | round(1) }}"
#    name: sensor_office_adc2
#    unit_of_measurement: "%h"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: !secret mqtt_default_expiration


