homeassistant:
  customize:
    sensor.sensor_study_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
    sensor.sensor_study_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      device_class: humidity
    sensor.sensor_study_pressure:
      friendly_name: Presión
      icon: mdi:weather-cloudy
    sensor.sensor_study_illumination:
      friendly_name: Iluminación
      icon: mdi:lightbulb-on

    sensor.sensor_study_snum:
      friendly_name: 'Sample # (estudio)'

    binary_sensor.sensor_study_mov1:
      friendly_name: 'Movimiento (estudio)'
    binary_sensor.sensor_study_online:
      friendly_name: Estudio Online

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_dev1_oled_lwt
    name: sensor_study_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: mqtt
    device_class: motion
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{{ value_json.sample.bin[0]}}"
    name: sensor_study_mov1
    qos: !secret mqtt_default_qos
    payload_on: 1
    payload_off: 0
    availability_topic: !secret mqtt_topic_esp_dev1_oled_lwt
    payload_available: "online"
    payload_not_available: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% else %}unknown{% endif %}"
    name: sensor_study_temperature
    unit_of_measurement: "°C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% else %}unknown{% endif %}"
    name: sensor_study_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{% if 'pres' in value_json.sample %}{{ value_json.sample.pres | round(1) }}{% else %}unknown{% endif %}"
    name: sensor_study_pressure
    unit_of_measurement: "mb"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{% if 'lux' in value_json.sample %}{{ value_json.sample.lux}}{% else %}unknown{% endif %}"
    name: sensor_study_illumination
    unit_of_measurement: "lx"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_dev1_oled_status
    value_template: "{{ value_json.sample.snum | int }}"
    unit_of_measurement: "sample"
#    json_attributes: 'ip,bssid,rssi,wifi_ap,clientid,status,network,ts,sample'
    json_attributes_topic: !secret mqtt_topic_esp_dev1_oled_status
    name: sensor_study_snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration
