homeassistant:
  customize:
    sensor.sensor_livingroom_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
    sensor.sensor_livingroom_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      device_class: humidity
    sensor.sensor_livingroom_pressure:
      friendly_name: Presión
      icon: mdi:weather-cloudy
    sensor.sensor_livingroom_illumination:
      friendly_name: Iluminación
      icon: mdi:lightbulb-on
    sensor.sensor_livingroom_snum:
      friendly_name: 'Sample # (salón)'

#    sensor.sensor_livingroom_adc1:
#      friendly_name: 'Sensor de humos 1'
#      icon: mdi:biohazard
#    sensor.sensor_livingroom_adc2:
#      friendly_name: 'Sensor de humos 2'
#      icon: mdi:biohazard

    binary_sensor.sensor_livingroom_mov1:
      friendly_name: 'Movimiento (salón)'
#    binary_sensor.sensor_livingroom_mov2:
#      friendly_name: 'Movimiento 2'
    binary_sensor.sensor_livingroom_online:
      friendly_name: Salón Online

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_livingroom_lwt
    name: sensor_livingroom_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

  - platform: mqtt
    device_class: motion
    state_topic: !secret mqtt_topic_esp_livingroom_status
    value_template: "{{ value_json.sample.bin[0]}}"
    name: sensor_livingroom_mov1
    qos: !secret mqtt_default_qos
    payload_on: 1
    payload_off: 0
    availability_topic: !secret mqtt_topic_esp_livingroom_lwt
    payload_available: "online"
    payload_not_available: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_livingroom_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% endif %}"
    name: sensor_livingroom_temperature
    unit_of_measurement: "°C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_livingroom_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% endif %}"
    name: sensor_livingroom_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_livingroom_status
    value_template: "{% if 'pres' in value_json.sample %}{{ value_json.sample.pres | round(1) }}{% endif %}"
    name: sensor_livingroom_pressure
    unit_of_measurement: "mb"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp_livingroom_status
#    value_template: "{% if 'lux' in value_json.sample %}{{ value_json.sample.lux}}{% endif %}"
#    name: sensor_livingroom_illumination
#    unit_of_measurement: "lx"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: !secret mqtt_default_expiration

  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_livingroom_status
    value_template: "{{ value_json.sample.snum | int }}"
    unit_of_measurement: "sample"
#    json_attributes: 'ip,bssid,rssi,wifi_ap,clientid,status,network,ts,sample'
    json_attributes_topic: !secret mqtt_topic_esp_livingroom_status
    name: sensor_livingroom_snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration_long

#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp_livingroom_status
#    value_template: "{{ (value_json.sample.adc[0] / 40.95) | round(1) }}"
#    name: sensor_livingroom_adc1
#    unit_of_measurement: "%h"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: !secret mqtt_default_expiration
#
#  - platform: mqtt
#    state_topic: !secret mqtt_topic_esp_livingroom_status
#    value_template: "{{ (value_json.sample.adc[1] / 40.95) | round(1) }}"
#    name: sensor_livingroom_adc2
#    unit_of_measurement: "%h"
#    qos: !secret mqtt_default_qos
#    force_update: true
#    expire_after: !secret mqtt_default_expiration

# switch:
#   - platform: mqtt
#     name: sensor_livingroom__switch_led
#     state_topic: !secret mqtt_topic_esp_livingroom_status
#     command_topic: !secret mqtt_topic_esp_galeria_command
#     value_template: "{{ value_json.status.led }}"
#     payload_on: "online"
#     payload_off: "offline"
#     availability_topic: !secret mqtt_topic_esp_livingroom_lwt
#     payload_available: "online"
#     payload_not_available: "offline"
#     #optimistic: false
#     qos: !secret mqtt_default_qos
#     retain: true
