homeassistant:
  customize:
    sensor.sensor_bathroom_ac_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
#      homebridge_name: Temperatura aseo
      homebridge_hidden: true
    sensor.sensor_bathroom_ac_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      homebridge_hidden: true
#      homebridge_name: Humedad aseo
#      homebridge_sensor_type: humidity
#    sensor.sensor_bathroom_ac_pressure:
#      friendly_name: Presión
#      icon: mdi:weather-cloudy
#      homebridge_hidden: true
    sensor.sensor_bathroom_ac_illumination:
      friendly_name: Iluminación
      icon: mdi:lightbulb-on
      homebridge_hidden: true

    sensor.sensor_bathroom_ac__snum:
      friendly_name: 'Sample # (aseo)'
      homebridge_hidden: true
    
#    binary_sensor.sensor_bathroom_ac_mov1:
#      friendly_name: 'Movimiento (aseo)'
#      homebridge_hidden: true
    binary_sensor.sensor_bathroom_ac_online:
      friendly_name: Aseo Online
      homebridge_hidden: true
    switch.ac_dry_contact:
      friendly_name: "Aire acondicionado"
      icon: mdi:air-conditioner
#      homebridge_hidden: true
      homebridge_name: Aire acondicionado

binary_sensor:
  - platform: mqtt
    device_class: connectivity
    state_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
    name: sensor_bathroom_ac_online
    qos: !secret mqtt_default_qos
    payload_on: "online"
    payload_off: "offline"

#  - platform: mqtt
#    device_class: motion
#    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
#    value_template: "{{ value_json.sample.bin[0]}}"
#    name: sensor_bathroom_ac_mov1
#    qos: !secret mqtt_default_qos
#    payload_on: 1
#    payload_off: 0
#    availability_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
#    payload_available: "online"
#    payload_not_available: "offline"

sensor:
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'temp' in value_json.sample %}{{ value_json.sample.temp | round(1) }}{% endif %}"
    name: sensor_bathroom_ac_temperature
    unit_of_measurement: "°C"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration
    
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'hum' in value_json.sample %}{{ value_json.sample.hum | round(1) }}{% endif %}"
    name: sensor_bathroom_ac_humidity
    unit_of_measurement: "%"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration
    
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{% if 'lux' in value_json.sample %}{{ value_json.sample.lux}}{% endif %}"
    name: sensor_bathroom_ac_illumination
    unit_of_measurement: "lx"
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration
    
  - platform: mqtt
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: "{{ value_json.sample.snum}}"
    unit_of_measurement: "sample"
#    json_attributes: 'status.version,status.wake,status.wake_reason,status.error,status.c_error'
    json_attributes: 'status,network,ts,sample'
    name: sensor_bathroom_ac__snum
    qos: !secret mqtt_default_qos
    force_update: true
    expire_after: !secret mqtt_default_expiration

  - platform: history_stats
    name: Horas de AC
    entity_id: climate.termostato_ac
    state: 'cool'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'

switch:
  - platform: mqtt
    name: ac_dry_contact
    state_topic: !secret mqtt_topic_esp_bathroom_ac_status
    value_template: '{"relay1": {{ value_json.sample.relays[0]}}}'
    command_topic: !secret mqtt_topic_esp_bathroom_ac_command
    payload_on: '{"relay1": 1}'
    payload_off: '{"relay1": 0}'
    availability_topic: !secret mqtt_topic_esp_bathroom_ac_lwt
    payload_available: "online"
    payload_not_available: "offline"
    optimistic: false
    qos: 2
    retain: true


climate:
  - platform: generic_thermostat
    name: Termostato AC
    heater: switch.ac_dry_contact
    ac_mode: True
    target_sensor: sensor.temperatura_ac
    min_temp: 18
    max_temp: 30
#    target_temp: 27
    cold_tolerance: 1.0
    hot_tolerance: 0.5
    min_cycle_duration:
      minutes: 10
    keep_alive:
      minutes: 5
    initial_operation_mode: "auto"
#    away_temp: 28
