# Etekcity outlets
homeassistant:
  customize:
    switch.cocina:
      icon: mdi:lightbulb
      friendly_name: LED Cocina
      homebridge_name: Cocina
    switch.tv_power:
      icon: mdi:power-plug
      friendly_name: TV y HomeCinema
      homebridge_name: Master TV
      homebridge_switch_type: outlet
      assumed_state: true
    switch.camara:
      icon: mdi:video
      friendly_name: Enchufe de videocámara
      homebridge_name: Cámara Video
      homebridge_switch_type: outlet
      assumed_state: true
    switch.altavoz:
      icon: mdi:speaker
      friendly_name: Enchufe Altavoz
      homebridge_name: Altavoz
      homebridge_switch_type: outlet
      assumed_state: true
    switch.test_switch:
      icon: mdi:home-automation
      friendly_name: Enchufe test
      homebridge_hidden: true
      assumed_state: true
    switch.test_switch_2:
      icon: mdi:home-automation
      friendly_name: Enchufe test 2 (old b.acs)
      homebridge_hidden: true
      assumed_state: true
    switch.office_floor:
      icon: mdi:home-automation
      friendly_name: Enchufe en estudio
      homebridge_hidden: true
      assumed_state: true
    switch.new_switch_2:
      icon: mdi:fan
      friendly_name: Ventilador
      homebridge_hidden: true
      assumed_state: true
    switch.new_switch_3:
      icon: mdi:power-plug
      friendly_name: Enchufe 3
      homebridge_hidden: true
      assumed_state: true

switch:
  - platform: rpi_rf
    gpio: 17
    name: Etekcity outlets
    switches:
#      cocina:
#        pulselength: 185
#        code_on: 4527411
#        code_off: 4527420
#        signal_repetitions: 20
      test_switch:
        pulselength: 185
        code_on: 4527555
        code_off: 4527564
        signal_repetitions: 80
#      camara:
#        pulselength: 185
#        code_on: 4527875
#        code_off: 4527884
#        signal_repetitions: 40
      office_floor:
        pulselength: 185
        code_on: 4529411
        code_off: 4529420
        signal_repetitions: 80
#      altavoz:
#        pulselength: 185
#        code_on: 4529411
#        code_off: 4529420
#        signal_repetitions: 30
      tv_power:
        pulselength: 185
        code_on: 4535555
        code_off: 4535564
        signal_repetitions: 80

      # new pack of Etekcity (3x)
#      bomba_circ_acs:
      test_switch_2:
        pulselength: 186
        code_on: 4478259
        code_off: 4478268
        signal_repetitions: 80
      altavoz:
        pulselength: 186
        code_on: 4478403
        code_off: 4478412
        signal_repetitions: 80
#      new_switch_3:
#        pulselength: 186
#        code_on: 4478723
#        code_off: 4478732
#        signal_repetitions: 60
  #    new_switch_4:  # no switch, only remote button
  #      pulselength: 186
  #      code_on: 4480259
  #      code_off: 4480268
  #      signal_repetitions: 20
  #    new_switch_5:  # no switch, only remote button
  #      pulselength: 186
  #      code_on: 4486403
  #      code_off: 4486412
  #      signal_repetitions: 20

#group:
#  Enchufes:
#    control: hidden
#    entities:
#      - switch.cocina
#      - switch.tv_power
#      - switch.camara
#      - switch.altavoz
#      - switch.bomba_circ_acs
#      - switch.calentador
#      - switch.switch_floor_office
#      - switch.new_switch_2
##      - switch.new_switch_2
##      - switch.new_switch_3