# Floorplan as custom panel and also as custom-state-card
# * needs `extra_html_url` in `frontend:` config *
#  extra_html_url:
#    - /local/custom_ui/state-card-floorplan.html
#    - /local/custom_ui/floorplan/ha-floorplan.html

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include ../floorplan.yaml
