homeassistant:
  customize:
    sensor.temperatura_interior:
      icon: mdi:thermometer
      hidden: true
    sensor.temperatura_stats_mean:
      friendly_name: Temperatura interior (rm)
      icon: mdi:thermometer
    sensor.temperatura_ac:
      icon: mdi:thermometer
      hidden: true
    sensor.temperatura_exterior:
      icon: mdi:thermometer

    sensor.temperatura_minima:
      friendly_name: Mínima diaria
      icon: mdi:thermometer
    sensor.temp_acs_max:
      friendly_name: ACS Máx Ret Solar
      icon: mdi:temperature-celsius

    sensor.humedad_interior:
      icon: mdi:water-percent
      hidden: true
      device_class: humidity
    sensor.humedad_stats_mean:
      friendly_name: Humedad interior (rm)
      icon: mdi:water-percent
      device_class: humidity
    sensor.humedad_exterior:
      icon: mdi:water-percent
      device_class: humidity

    input_boolean.ac_target_include_livingroom:
      friendly_name: AC Salón
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_study:
      friendly_name: AC Estudio
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_office:
      friendly_name: AC Office
      icon: mdi:toggle-switch
    input_boolean.ac_target_include_bedroom:
      friendly_name: AC Dormitorio
      icon: mdi:toggle-switch

sensor:

  - platform: min_max
    type: mean
    name: Temperatura AC
    entity_ids:
      -  sensor.sensor_livingroom_temperature
      -  sensor.sensor_study_temperature
      -  sensor.sensor_office_temperature
      -  sensor.dormitorio_temperature_rpi2mpd

  - platform: min_max
    type: mean
    name: Temperatura interior
    entity_ids:
      -  sensor.sensor_kitchen_temperature
      -  sensor.sensor_study_temperature
      -  sensor.sensor_office_temperature
      -  sensor.sensor_livingroom_temperature
      -  sensor.dormitorio_temperature_rpi2mpd
      -  sensor.sensor_bathroom_ac_temperature

  - platform: min_max
    type: min
    name: Temperatura exterior
    entity_ids:
      -  sensor.sensor_terraza_temperature
      -  sensor.sensor_galeria_temperature

  - platform: min_max
    type: mean
    name: Humedad interior
    entity_ids:
      -  sensor.sensor_kitchen_humidity
      -  sensor.sensor_study_humidity
      -  sensor.sensor_office_humidity
      -  sensor.sensor_livingroom_humidity
      -  sensor.dormitorio_humidity_rpi2mpd
      -  sensor.sensor_bathroom_ac_humidity

  - platform: min_max
    type: mean
    name: Humedad exterior
    entity_ids:
      -  sensor.sensor_terraza_humidity
      -  sensor.sensor_galeria_humidity

  - platform: statistics
    entity_id: sensor.temperatura_interior
    name: Temperatura (stats)
    sampling_size: 30
    max_age:
      minutes: 15

  - platform: statistics
    name: Humedad (stats)
    sampling_size: 30
    entity_id: sensor.humedad_interior
    max_age:
      minutes: 15

#  - sensor.temperatura_minima
  - platform: influxdb
    host: !secret influxdb_host
    port: !secret influxdb_port
    username: !secret influxdb_user
    password: !secret influxdb_pass
    # ssl: true
    # verify_ssl: true
    default_measurement: state
    queries:
      - name: "Temperatura mínima"
        database: !secret influxdb_db
        unit_of_measurement: °C
        value_template: '{{ value | round(1) }}'
        field: value #select
        group_function: min
        measurement: '"°C"' #from
        where: '"entity_id" = ''temperatura_exterior'' and time > now() - 24h' #where

  - platform: influxdb
    host: !secret influxdb_host
    port: !secret influxdb_port
    username: !secret influxdb_user
    password: !secret influxdb_pass
    # ssl: true
    # verify_ssl: true
    default_measurement: state
    queries:
      - name: temp_acs_max
        database: !secret influxdb_db
        unit_of_measurement: °C
        value_template: '{{ value | round(1) }}'
        field: value #select
        group_function: max
        measurement: '"°C"' #from
        where: '"entity_id" = ''sensor_acs_probe_5'' and time > now() - 24h' #where