homekit:
  name: Casa
  filter:
    include_domains:
      - alarm_control_panel
      - cover
      - climate
      - vacuum
    include_entities:
      - media_player.kodi_tv
      - light.yeelight_strip_7811dca21ecf

      - light.hall_light

      - switch.calentador
      - switch.bomba_circ_acs

#      - binary_sensor.electricity_high_cost_interval

      - sensor.sensor_galeria_humidity
      - sensor.sensor_galeria_temperature
      - sensor.sensor_kitchen_humidity
      - sensor.sensor_kitchen_temperature
      - sensor.sensor_livingroom_humidity
      - sensor.sensor_livingroom_temperature
      - sensor.sensor_office_humidity
      - sensor.sensor_office_temperature
      - sensor.sensor_study_humidity
      - sensor.sensor_study_temperature
      - sensor.sensor_terraza_humidity
      - sensor.sensor_terraza_temperature
      - sensor.dormitorio_humidity_rpi2mpd
      - sensor.dormitorio_temperature_rpi2mpd

      - script.play_kodi_pvr
      - script.start_tvshows_mode
      - script.quick_cool_session
      - script.quick_heat_session
      - script.start_vacuum
#      - scene.golpe_de_frio
#      - scene.la_caja_tonta
#      - scene.modo_series
  entity_config:
    media_player.kodi_tv:
      name: Tele
      feature_list:
        - feature: on_off
#        - feature: play_pause
#        - feature: play_stop
    switch.bomba_circ_acs:
      type: valve
      name: Bomba ACS
    switch.calentador:
      type: shower
      name: Calentador

    script.play_kodi_pvr:
      name: La caja tonta
    script.start_tvshows_mode:
      name: Modo series
    script.quick_cool_session:
      name: Golpe de frío
