# HUE LIGHTS
homeassistant:
  customize:
    input_number.light_main_slider_salon:
      friendly_name: Brillo
      icon: mdi:brightness-7
    input_number.light_temp_slider_salon:
      friendly_name: Temperatura de color
      icon: mdi:temperature-kelvin
    automation.brillo_salon_sync:
      icon: mdi:brightness-auto
      friendly_name: Sync brillo bola grande

    light.bola_grande:
      icon: mdi:ceiling-light
    light.terraza:
      icon: mdi:lightbulb-outline
    light.hue_habitacion:
      icon: mdi:ceiling-light
    light.aura_habitacion:
      icon: mdi:lava-lamp
    light.pie_tv:
      icon: mdi:lamp
    light.pie_sofa:
      icon: mdi:lamp
    light.cuenco:
      icon: mdi:lava-lamp
    light.lamparita:
      icon: mdi:lava-lamp
    light.flexo:
      icon: mdi:lightbulb-outline
    light.central:
      icon: mdi:ceiling-light
    light.go:
      icon: mdi:lava-lamp
    light.tira:
      icon: mdi:dots-horizontal

hue:
  bridges:
    - host: !secret hue_bridge_host
      allow_unreachable: true

## sensor.hue_dimmer_switch
sensor:
- platform: hue_dimmer


input_number:
  # Master Sliders Salón (brillo y Tª color)
  light_main_slider_salon:
    name: Brillo salón
  #  initial: 0
    min: 0
    max: 255
    step: 1
  light_temp_slider_salon:
    name: Blanco Salón
  #  initial: 10
    min: 0
    max: 100
    step: 1

input_select:
  salon_light_scene:
    name: Escena de luz
    options:
     - Concentración
     - Energía
     - Relax
     - Lectura
     - Estudio
#     - Comida
#     - Cena
     - Atardecer
     - Aurora boreal
     - Flor primaveral
     - Ocaso tropical
     - TV Night
     - 'OFF'
    initial: Energía
    icon: mdi:lightbulb
