####################################################
#                     IFTTT                        #
####################################################
#For example, set the body of the IFTTT webhook to:
#
#{ "action": "call_service", "service": "light.turn_on", "entity_id": "light.living_room" }
#You then need to consume that incoming information with the following automation:
#
#automation:
#  trigger:
#    platform: event
#    event_type: ifttt_webhook_received
#    event_data:
#      action: call_service
#  action:
#    service_template: '{{ trigger.event.data.service }}'
#    data_template:
#      entity_id: '{{ trigger.event.data.entity_id }}'

ifttt:
  key: !secret ifttt_key
