# psychrometrics custom component from psychrochartweb
homeassistant:
  customize:
    camera.psychrometric_chart:
      friendly_name: Diagrama psicrométrico

camera:
  - platform: generic
    name: psychrometric_chart
    still_image_url: !secret psychrocam_svgchart_url
    content_type: 'image/svg+xml'
