# psychrometrics custom component from PsychroCam
homeassistant:
  customize:
    camera.psychrometric_chart:
      friendly_name: Diagrama psicrométrico
    sensor.psychrometric_evolution:
      hidden: True
  customize_glob:
    sensor.temp_change_*:
      icon: mdi:delta

camera:
  - platform: generic
    name: psychrometric_chart
    still_image_url: !secret psychrocam_svgchart_url
    content_type: 'image/svg+xml'

sensor:
  - platform: rest
    name: psychrometric_evolution
    resource: !secret psychrocam_ha_evo_url
    unit_of_measurement: "sample"
    json_attributes:
      - pressure_kPa
      - Office
      - Salón
      - Dormitorio
      - Cocina
      - Estudio
      - Aseo
      - Terraza
      - Galería
      - Previsto
    scan_interval: 60
    value_template: '{{ value_json.num_points | int }}'

  - platform: template
    sensors:
      temp_change_office:
        friendly_name: '∆T Office'
        value_template: '{% if "Office" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Office"]["first"]["∆T [°C/h]"] | round(2)  }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_kitchen:
        friendly_name: '∆T Cocina'
        value_template: '{% if "Cocina" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Cocina"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_livingroom:
        friendly_name: '∆T Salón'
        value_template: '{% if "Salón" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Salón"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_bedroom:
        friendly_name: '∆T Dormitorio'
        value_template: '{% if "Dormitorio" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Dormitorio"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_bathroom_ac:
        friendly_name: '∆T Aseo'
        value_template: '{% if "Aseo" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Aseo"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_study:
        friendly_name: '∆T Estudio'
        value_template: '{% if "Estudio" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Estudio"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_terraza:
        friendly_name: '∆T Terraza'
        value_template: '{% if "Terraza" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Terraza"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution
      temp_change_galeria:
        friendly_name: '∆T Galería'
        value_template: '{% if "Galería" in states.sensor.psychrometric_evolution.attributes %}{{ states.sensor.psychrometric_evolution.attributes["Galería"]["first"]["∆T [°C/h]"] | round(2) }}{% endif %}'
        unit_of_measurement: '°C/h'
        entity_id: sensor.psychrometric_evolution


#psychrometrics:
#  scan_interval: 30
#  altitude: 10
##  pressure_kpa: 975
#  evolution_arrows_minutes: 180
#  remote_api:
#    base_url: !secret master_base_url
#    api_password: !secret master_api_password
#    port: 443
#    use_ssl: True
#  interior:
#    Salón:
#      - sensor.sensor_livingroom_temperature, sensor.sensor_livingroom_humidity
#    Dormitorio:
##      - sensor.sensor_bedroom_temperature, sensor.sensor_bedroom_humidity
#      - sensor.dormitorio_temperature_rpi2mpd, sensor.dormitorio_humidity_rpi2mpd
#    Cocina:
#      - sensor.sensor_kitchen_temperature, sensor.sensor_kitchen_humidity
#    Office:
#      - sensor.sensor_office_temperature, sensor.sensor_office_humidity
#    Estudio:
#      - sensor.sensor_study_temperature, sensor.sensor_study_humidity
#    Aseo:
#      - sensor.sensor_bathroom_ac_temperature, sensor.sensor_bathroom_ac_humidity
#  exterior:
#    Galería:
#      - sensor.sensor_galeria_temperature, sensor.sensor_galeria_humidity
#    Terraza:
#      - sensor.sensor_terraza_temperature, sensor.sensor_terraza_humidity
##      - sensor.sensor_galeria_temperature, sensor.sensor_galeria_humidity
##      - sensor.sensor_terraza_temperature, sensor.sensor_terraza_humidity
#  weather:
#      - sensor.dark_sky_temperature, sensor.dark_sky_humidity
##      - sensor.villena_temperature, sensor.villena_humidity


#automation:
#- alias: Notificación de final de ventilación natural
#  trigger:
#    platform: state
#    entity_id: binary_sensor.close_house
#    from: 'on'
#    to: 'off'
#  action:
#    - service: telegram_bot.send_message
#      data_template:
#        title: '*Cierre y oscurecimiento de ventanas*'
#        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
#        message: >
#          _Se recomienda aislar la casa lo máximo posible para evitar el recalentamiento gratuito_.
#          Las temperaturas actuales son de *{{states.sensor.house_delta_temperature.attributes['Exterior'] | round(1)}} °C en el exterior* (estimados {{states.sensor.house_delta_temperature.attributes['Exterior Est.'] | round(1)}} °C), y *{{states.sensor.house_delta_temperature.attributes['Interior'] | round(1)}} °C en el interior*, ∆T={{states.sensor.house_delta_temperature.state}} °C.
#          (∆ por zonas: {% for attr in states.sensor.house_delta_temperature.attributes -%}{%- if attr not in ['homebridge_hidden', 'icon', 'friendly_name', '∆T with estimated exterior', 'Exterior' , 'attribution' , 'Interior' , 'Exterior Est.', 'unit_of_measurement'] -%} {{attr}}: {{states.sensor.house_delta_temperature.attributes[attr]}} °C, {%- endif -%}{%- endfor -%})
#
#        inline_keyboard:
#          - Ventilador ON:/service_call homeassistant/turn_on switch.new_switch_2, Ventilador OFF:/service_call homeassistant/turn_off switch.new_switch_2
#        disable_notification: false
#        disable_web_page_preview: false
#
#- alias: Notificación de inicio de ventilación natural
#  trigger:
#    platform: state
#    entity_id: binary_sensor.close_house
#    from: 'off'
#    to: 'on'
#  action:
#    - service: telegram_bot.send_message
#      data_template:
#        title: '*Apertura de ventanas*'
#        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
#        message: >
#          _Se recomienda ventilar la casa para refrescarla_.
#          Las temperaturas actuales son de *{{states.sensor.house_delta_temperature.attributes['Exterior'] | round(1)}} °C en el exterior* (estimados {{states.sensor.house_delta_temperature.attributes['Exterior Est.'] | round(1)}} °C), y *{{states.sensor.house_delta_temperature.attributes['Interior'] | round(1)}} °C en el interior*, ∆T={{states.sensor.house_delta_temperature.state}} °C.
#          (∆ por zonas: {% for attr in states.sensor.house_delta_temperature.attributes -%}{%- if attr not in ['homebridge_hidden', 'icon', 'friendly_name', '∆T with estimated exterior', 'Exterior' , 'attribution' , 'Interior' , 'Exterior Est.', 'unit_of_measurement'] -%} {{attr}}: {{states.sensor.house_delta_temperature.attributes[attr]}} °C, {%- endif -%}{%- endfor -%})
#
#        inline_keyboard:
#          - Ventilador ON:/service_call homeassistant/turn_on switch.new_switch_2, Ventilador OFF:/service_call homeassistant/turn_off switch.new_switch_2
#        disable_notification: false
#        disable_web_page_preview: false


#group:
#  Aislamiento:
#    entities:
#      - camera.psychrometric_chart
#      - sensor.psychrometric_evolution
#      - binary_sensor.floorplan
#      - sensor.temp_change_office
#      - sensor.temp_change_kitchen
#      - sensor.temp_change_livingroom
#      - sensor.temp_change_bedroom
#      - sensor.temp_change_bathroom_ac
#      - sensor.temp_change_study
#      - sensor.temp_change_terraza
#      - sensor.temp_change_galeria
#
#      - sensor.house_delta_temperature
#      - binary_sensor.close_house