###############################################################################
# enerPI current meter
###############################################################################
homeassistant:
  customize:
    sensor.nashome_status:
      friendly_name: QNAP Status
    sensor.nashome_cpu_usage:
      friendly_name: QNAP CPU Usage
    sensor.nashome_memory_usage:
      friendly_name: QNAP Memory Usage
    sensor.nashome_system_temperature:
      friendly_name: QNAP Temperature
    sensor.nashome_network_down_eth0:
      friendly_name: QNAP Download
    sensor.nashome_network_up_eth0:
      friendly_name: QNAP Upload
    sensor.nashome_volume_used_datavol1:
      friendly_name: Disk used

sensor:
  - platform: qnap
    host: !secret nas_qnap_host
    username: !secret nas_qnap_username
    password: !secret nas_qnap_password
    nics: eth0
    scan_interval: 60
    timeout: 10
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - system_temp
#      - drive_temp
#      - drive_smart_status
      - network_tx
      - network_rx
      - volume_percentage_used

