###############################################################################
# SONOS
###############################################################################

sonos:
  media_player:
    hosts:
      - !secret sonos_host_1
      - !secret sonos_host_2
