homeassistant:
  customize:
    binary_sensor.local_pir:
      friendly_name: Movimiento (cuadro)
      device_class: motion
      homebridge_hidden: true

    sensor.local_htu21d_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
      homebridge_hidden: True
    sensor.local_htu21d_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
#      homebridge_sensor_type: humidity
      homebridge_hidden: True

    sensor.local_light_level:
      friendly_name: Iluminación
      icon: mdi:lightbulb
      device_class: light
#      homebridge_sensor_type: light
      homebridge_hidden: True

    sensor.hass_cpu_temperature:
      homebridge_hidden: True
    sensor.kodi_cpu_temperature:
      homebridge_hidden: True
    sensor.rpi3dev1_cpu_temperature:
      homebridge_hidden: True
    sensor.rpi3dev2_cpu_temperature:
      homebridge_hidden: True
    sensor.rpi3dev3_cpu_temperature:
      homebridge_hidden: True
    sensor.enerpi_cpu_temperature:
      homebridge_hidden: True
    sensor.memory_free:
      homebridge_hidden: True
    sensor.processor_use:
      homebridge_hidden: True
    sensor.disk_use_percent_:
      homebridge_hidden: True
    sensor.last_boot:
      homebridge_hidden: True

    sensor.pihole_ads_blocked_today:
      friendly_name: Ads blocked today
    sensor.pihole_ads_percentage_blocked_today:
      friendly_name: Ads (%) blocked today
    sensor.pihole_dns_unique_clients:
      friendly_name: DNS unique clients
    sensor.pihole_dns_queries_today:
      friendly_name: DNS queries today
    sensor.pihole_dns_unique_domains:
      friendly_name: DNS unique domains

    input_boolean.eu_presence:
      icon: mdi:human-male
    input_boolean.carmen_presence:
      icon: mdi:human-female

    sensor.iphone_battery_state:
      friendly_name: iPhone X (Batt state)
      homebridge_hidden: True
    sensor.iphone_battery_level:
      friendly_name: iPhone X (Battery)
      homebridge_hidden: True
    sensor.iphone_de_maria_del_carmen_battery_state:
      friendly_name: iPhone SE (Batt state)
      homebridge_hidden: True
    sensor.iphone_de_maria_del_carmen_battery_level:
      friendly_name: iPhone SE (Battery)
      homebridge_hidden: True
    sensor.ipad_de_eugenio_battery_state:
      friendly_name: iPad (Batt state)
      homebridge_hidden: True
    sensor.ipad_de_eugenio_battery_level:
      friendly_name: iPad (Battery)
      homebridge_hidden: True

    sensor.sensor_power__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_bathroom_ac__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_bedroom__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_covers__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_galeria__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_hall__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_study__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_office__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_livingroom__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_kitchen__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand
    sensor.sensor_terraza__time_drift:
      homebridge_hidden: true
      icon: mdi:timer-sand

  # Customize entities matching a pattern
  customize_glob:
    "sensor.pihole*":
      homebridge_hidden: True
    "sensor.speedtest*":
      homebridge_hidden: True
      icon: mdi:speedometer

map:

# This will override the default home zone
zone:
- name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 125
  icon: mdi:castle

- name: !secret z1_name
  latitude: !secret z1_latitude
  longitude: !secret z1_longitude
  radius: !secret z1_radius
  icon: !secret z1_icon

- name: !secret z2_name
  latitude: !secret z2_latitude
  longitude: !secret z2_longitude
  radius: !secret z2_radius
  icon: !secret z2_icon

input_boolean:
  eu_presence:
    name: Eu en casa
  carmen_presence:
    name: Carmen en casa

binary_sensor:
  - platform: rpi_gpio
    name: Movimiento
    device_class: motion
    ports:
      18: local_pir
    bouncetime: 50
    pull_mode: "UP"
  #  invert_logic: true

sensor:
- platform: htu21d
  name: local_htu21d
  scan_interval: 45

- platform: command_line
  name: HASS CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60

- platform: command_line
  name: KODI CPU Temperature
  command: !secret ssh_cmd_rpi_temp_kodi
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 180

- platform: command_line
  name: RPI3Dev1 CPU Temperature
  command: !secret ssh_cmd_rpi_temp_rpi3dev1
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 180

- platform: command_line
  name: RPI3Dev2 CPU Temperature
  command: !secret ssh_cmd_rpi_temp_rpi3dev2
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 180

#- platform: command_line
#  name: RPI3Dev3 CPU Temperature
#  command: !secret ssh_cmd_rpi_temp_rpi3dev3
#  unit_of_measurement: "°C"
#  value_template: '{{ value | multiply(0.001) | round(1) }}'
#  scan_interval: 180

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
  scan_interval: 30

- platform: template
  sensors:
#    {{states.variable.speedtest_data.attributes.ping.state}}
#    {{states.variable.speedtest_data.attributes.ping.attributes}}
#    {{states.variable.speedtest_data.attributes.download.state}}
#    {{states.variable.speedtest_data.attributes.download.attributes}}
#    {{states.variable.speedtest_data.attributes.upload.state}}
#    {{states.variable.speedtest_data.attributes.upload.attributes}}
    speedtest_ping:
      friendly_name: "Speedtest Ping"
      unit_of_measurement: 'ms'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.ping.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_upload:
      friendly_name: "Speedtest Upload"
      unit_of_measurement: 'Mbit/s'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.upload.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_download:
      unit_of_measurement: 'Mbit/s'
      friendly_name: "Speedtest Download"
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.download.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data

    sensor_power__time_drift:
      value_template: >
        {% if states.sensor.esp32ener_power.attributes.ts %}{{(as_timestamp(states.sensor.esp32ener_power.last_updated)
        - as_timestamp(strptime(states.sensor.esp32ener_power.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}{% endif %}
      unit_of_measurement: "s"
      friendly_name: Time sync Current meter
      entity_id: sensor.esp32ener_power
    sensor_bathroom_ac__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_bathroom_ac__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_bathroom_ac__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Baño
      entity_id: sensor.sensor_bathroom_ac__snum
    sensor_covers__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_covers__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_covers__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Persianas
      entity_id: sensor.sensor_covers__snum
    sensor_bedroom__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_bedroom__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_bedroom__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Dormitorio
      entity_id: sensor.sensor_bedroom__snum
    sensor_galeria__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_galeria__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_galeria__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Galería
      entity_id: sensor.sensor_galeria__snum
    sensor_hall__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_hall__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_hall__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Hall
      entity_id: sensor.sensor_hall__snum
    sensor_study__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_study__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_study__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Estudio
      entity_id: sensor.sensor_study__snum
    sensor_office__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_office__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_office__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Office
      entity_id: sensor.sensor_office__snum
    sensor_livingroom__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_livingroom__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_livingroom__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Salón
      entity_id: sensor.sensor_livingroom__snum
    sensor_kitchen__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_kitchen__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_kitchen__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Cocina
      entity_id: sensor.sensor_kitchen__snum
    sensor_terraza__time_drift:
      value_template: >
        {{(as_timestamp(states.sensor.sensor_terraza__snum.last_updated)
        - as_timestamp(strptime(states.sensor.sensor_terraza__snum.attributes.ts,
              "%Y/%m/%d %H:%M:%S.%f"))) | round(2)}}
      unit_of_measurement: "s"
      friendly_name: Time sync Terraza
      entity_id: sensor.sensor_terraza__snum

#- platform: speedtest
#  minute:
#    - 35
#  monitored_conditions:
#    - ping
#    - download
#    - upload


shell_command:
  # Init SSH keys
  cmd_init_ssh_identity: '/config/shell/start_ssh_keys.sh'

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.1-240
  exclude:
    - !secret local_ip
    - '127.0.0.1'
  home_interval: 30
# # If new discovered devices are tracked by default (default: yes)
#   track_new_devices: no
#   # Seconds between each scan for new devices (default: 12)
  interval_seconds: 60
#   # Seconds to wait till marking someone as not home after not being seen
#   # (default: 180)
  consider_home: 300
  track_new_devices: yes

- platform: bluetooth_tracker

- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
