homeassistant:
  customize:

    binary_sensor.local_pir:
      friendly_name: Movimiento (cuadro)
      device_class: motion
      homebridge_hidden: true

    sensor.local_htu21d_temperature:
      friendly_name: Temperatura
      icon: mdi:thermometer
    sensor.local_htu21d_humidity:
      friendly_name: Humedad
      icon: mdi:water-percent
      homebridge_sensor_type: humidity
  
    sensor.local_light_level:
      friendly_name: Iluminación
      icon: mdi:lightbulb
      device_class: light
      homebridge_sensor_type: light
  
    sensor.hass_cpu_temperature:
      homebridge_hidden: True
    sensor.kodi_cpu_temperature:
      homebridge_hidden: True
    sensor.enerpi_cpu_temperature:
      homebridge_hidden: True
    sensor.ram_free:
      homebridge_hidden: True
    sensor.cpu_use:
      homebridge_hidden: True
    sensor.disk_use_:
      homebridge_hidden: True
    sensor.last_boot:
      homebridge_hidden: True

    sensor.pihole_ads_blocked_today:
      friendly_name: Ads blocked today
    sensor.pihole_ads_percentage_blocked_today:
      friendly_name: Ads (%) blocked today
    sensor.pihole_dns_unique_clients:
      friendly_name: DNS unique clients
    sensor.pihole_dns_queries_today:
      friendly_name: DNS queries today
    sensor.pihole_dns_unique_domains:
      friendly_name: DNS unique domains

    sensor.yw_day1_condition:
      friendly_name: Mañana
    sensor.yw_day1_temperature_min:
      friendly_name: Mínima mañana
    sensor.yw_day1_temperature_max:
      friendly_name: Máxima mañana
    sensor.yw_day2_condition:
      friendly_name: Pasado mañana
    sensor.yw_day2_temperature_min:
      friendly_name: Mínima pasado mañana
    sensor.yw_day2_temperature_max:
      friendly_name: Máxima pasado mañana

    sensor.dark_sky_summary:
      friendly_name: Resumen
    sensor.dark_sky_hourly_summary:
      friendly_name: Resumen horario
    sensor.dark_sky_daily_summary:
      friendly_name: Forecast
    sensor.dark_sky_temperature:
      friendly_name: Temperatura

    camera.weather_svg:
      friendly_name: !secret weather_svg_cam_name

    input_number.max_humidity:
      friendly_name: Humedad Máx.
      icon: mdi:water

    input_boolean.eu_presence:
      icon: mdi:human-male
    input_boolean.carmen_presence:
      icon: mdi:human-female

    binary_sensor.workday_sensor:
      homebridge_hidden: True

    sensor.ip_externa:
      homebridge_hidden: True
      icon: mdi:map-marker
    sensor.iphone_battery_state:
      friendly_name: iPhone X (Batt state)
      homebridge_hidden: True
    sensor.iphone_battery_level:
      friendly_name: iPhone X (Battery)
      homebridge_hidden: True
    sensor.iphone_de_maria_del_carmen_battery_state:
      friendly_name: iPhone SE (Batt state)
      homebridge_hidden: True
    sensor.iphone_de_maria_del_carmen_battery_level:
      friendly_name: iPhone SE (Battery)
      homebridge_hidden: True
    sensor.ipad_de_eugenio_battery_state:
      friendly_name: iPad (Batt state)
      homebridge_hidden: True
    sensor.ipad_de_eugenio_battery_level:
      friendly_name: iPad (Battery)
      homebridge_hidden: True
    sensor.season:
      homebridge_hidden: True
      icon: mdi:tree

  # Customize entities matching a pattern
  customize_glob:
    "sensor.pihole*":
      homebridge_hidden: True
    "sensor.yw_day*":
      homebridge_hidden: True
    "sensor.dark_sky_*":
      homebridge_hidden: True
    "sensor.dark_sky_hum*":
      friendly_name: Humedad
    "sensor.dark_sky_press*":
      friendly_name: Presión
    "sensor.dark_sky_dew_point*":
      friendly_name: Tª de rocío
    "sensor.dark_sky_apparent_temp*":
      friendly_name: Temperatura aparente
    "sensor.dark_sky_daily_high_apparent_temp*":
      friendly_name: Máxima diaria aparente
      icon: mdi:arrow-collapse-up
    "sensor.dark_sky_daily_high_temp*":
      friendly_name: Máxima diaria
      icon: mdi:arrow-collapse-up
    "sensor.dark_sky_daily_low_temp*":
      friendly_name: Mínima diaria
      icon: mdi:arrow-collapse-down
    "sensor.speedtest*":
      homebridge_hidden: True


# This will override the default home zone
zone:
- name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 125
  icon: mdi:castle

- name: !secret z1_name
  latitude: !secret z1_latitude
  longitude: !secret z1_longitude
  radius: !secret z1_radius
  icon: !secret z1_icon

- name: !secret z2_name
  latitude: !secret z2_latitude
  longitude: !secret z2_longitude
  radius: !secret z2_radius
  icon: !secret z2_icon

input_boolean:
  eu_presence:
    name: Eu en casa
  carmen_presence:
    name: Carmen en casa

binary_sensor:
  - platform: rpi_gpio
    name: Movimiento
    device_class: motion
    ports:
      18: local_pir
    bouncetime: 50
    pull_mode: "UP"
  #  invert_logic: true

  # binary_sensor.workday_sensor
  - platform: workday
    country: !secret country_code
    province: !secret province_code
  #  workdays: List of workdays (defaults to mon, tue, wed, thu, fri).
  #  excludes: List of workday excludes (defaults to sat, sun, holiday).

sensor:
- platform: rest
  resource: http://ip.jsontest.com
  name: IP Externa
  value_template: '{{ value_json.ip }}'
  scan_interval: 60

- platform: season

- platform: htu21d
  name: local_htu21d
  scan_interval: 45

- platform: darksky
  api_key: !secret darksky_api_key
  forecast:
    - 1
    - 2
    - 3
  monitored_conditions:
    - summary
    - hourly_summary
    - daily_summary
    - temperature
    - temperature_max
    - temperature_min
    - apparent_temperature
#    - apparent_temperature_max
#    - dew_point
    - humidity
    - pressure
  update_interval: "0:20:00"
  scan_interval: 1200
#    minutes: 20

- platform: command_line
  name: HASS CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60

- platform: command_line
  name: KODI CPU Temperature
  command: !secret ssh_cmd_rpi_temp_kodi
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 180

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
  scan_interval: 30

- platform: pi_hole
  host: 192.168.1.10:81
  monitored_conditions:
    - dns_queries_today
    - ads_blocked_today
    - ads_percentage_today
    - unique_clients
    - unique_domains
#    - domains_being_blocked
  scan_interval: 180

#- platform: speedtest
#  minute:
#    - 35
#  monitored_conditions:
#    - ping
#    - download
#    - upload


shell_command:
  # Init SSH keys
  cmd_init_ssh_identity: '/config/shell/start_ssh_keys.sh'

device_tracker:
- platform: nmap_tracker
  hosts: 192.168.1.1-100
  exclude:
    - !secret local_ip
    - '127.0.0.1'
  home_interval: 30
# # If new discovered devices are tracked by default (default: yes)
#   track_new_devices: no
#   # Seconds between each scan for new devices (default: 12)
  interval_seconds: 60
#   # Seconds to wait till marking someone as not home after not being seen
#   # (default: 180)
  consider_home: 300
  track_new_devices: yes

- platform: bluetooth_tracker

- platform: owntracks
  max_gps_accuracy: 200
  waypoints: True
