homeassistant:
  customize:
    input_select.esp_command:
      icon: mdi:developer-board
    input_select.esp_modules:
      icon: mdi:developer-board
    sensor.processor_use:
      icon: mdi:chip

  # Customize entities matching a pattern
  customize_glob:
    "sensor.speedtest*":
      icon: mdi:speedometer
    "sensor.sensor_*_time_drift":
      icon: mdi:timer-sand


#binary_sensor:
#  - platform: rpi_gpio
#    name: Movimiento
#    device_class: motion
#    ports:
#      18: local_pir
#    bouncetime: 50
#    pull_mode: "UP"
#  #  invert_logic: true

timer:
  alarm_auto_on:
    duration: '00:10:00'
    icon: mdi:alarm-check
  deadman:
    duration: '01:00:00'
    icon: mdi:emoticon-dead

variable:
  speedtest_data:
    value: 0
    attributes:
      icon: mdi:speedometer
#    restore: true

input_select:
  esp_command:
    name: Comandos
    options:
     - Restart
     - Wifi_scan
  esp_modules:
    name: Módulos
    options:
     - Terraza
     - Persianas
     - Salón
     - Dormitorio
     - Baño
     - Office
     - Estudio
     - Hall
     - Cocina
     - Galería
     - Cuadro

sensor:
- platform: time_date
  display_options:
  - 'time_utc'
  - 'date_time'

#  Removed because of hassio OS incompatibility:
#- platform: htu21d
#  name: local_htu21d
#  scan_interval: 45

- platform: command_line
  name: HASS CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 60

- platform: command_line
  name: RPI3Dev1 CPU Temperature
  command: !secret ssh_cmd_rpi_temp_rpi3dev1
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(1) }}'
  scan_interval: 180

#- platform: command_line
#  name: RPI3Dev2 CPU Temperature
#  command: !secret ssh_cmd_rpi_temp_rpi3dev2
#  unit_of_measurement: "°C"
#  value_template: '{{ value | multiply(0.001) | round(1) }}'
#  scan_interval: 180

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /
    - type: memory_free
    - type: processor_use
    - type: last_boot
  scan_interval: 30

- platform: template
  sensors:
    speedtest_ping:
      friendly_name: "Speedtest Ping"
      unit_of_measurement: 'ms'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.ping.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_upload:
      friendly_name: "Speedtest Upload"
      unit_of_measurement: 'Mbit/s'
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.upload.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data
    speedtest_download:
      unit_of_measurement: 'Mbit/s'
      friendly_name: "Speedtest Download"
      value_template: '{% if "ping" in states.variable.speedtest_data.attributes %}{{states.variable.speedtest_data.attributes.download.state}}{% else %}unknown{% endif %}'
      entity_id: variable.speedtest_data

#- platform: speedtest
#  minute:
#    - 35
#  monitored_conditions:
#    - ping
#    - download
#    - upload


shell_command:
  # Init SSH keys
  cmd_init_ssh_identity: '/config/shell/start_ssh_keys.sh'
