###############################################################################
# KODI - OSMC - Hyperion Control
###############################################################################
homeassistant:
  customize:
    media_player.kodi:
      hidden: true
    input_boolean.kodi_tv_state:
      hidden: true
    media_player.kodi_tv:
      friendly_name: Kodi LibreElec
    script.play_kodi_pvr:
      friendly_name: Enciende la caja tonta
      icon: mdi:television-guide

    script.cec_tv_on:
      icon: mdi:television
    script.cec_tv_off:
      icon: mdi:television-off
    script.update_library:
      icon: mdi:refresh
    script.stop_kodi:
      icon: mdi:stop
    script.quit_kodi:
      icon: mdi:close
    script.recent_episodes:
      icon: mdi:play-circle
    script.recent_movies:
      icon: mdi:movie
    script.pvr_channels:
      icon: mdi:play-box-outline
    script.pvr_recordings:
      icon: mdi:television-classic
    input_select.kodi_results:
      icon: mdi:kodi
    input_text.q_youtube:
      icon: mdi:youtube
    input_select.youtube_videos:
      icon: mdi:youtube

input_boolean:
  kodi_tv_state:

#switch:
#  - platform: command_line
#    scan_interval: 120
#    switches:
#      toggle_kodi_ambilight:
#        command_on: '/config/shell/switch_kodi_hyperion.sh 1'
#        command_off: '/config/shell/switch_kodi_hyperion.sh 0'
#        command_state: '/config/shell/switch_kodi_hyperion.sh'
#        friendly_name: KODI Ambilight
#        value_template: '{{ value_json == 1 }}'
#      toggle_config_kodi_ambilight:
#        command_on: '/config/shell/switch_kodi_hyperion.sh set_hue6'
#        command_off: '/config/shell/switch_kodi_hyperion.sh set_hue4'
#        command_state: '/config/shell/switch_kodi_hyperion.sh num_lights'
#        friendly_name: KODI Ambilight INMERSION
#        value_template: '{{ value_json == 6 }}'

media_player:
- platform: firetv
  name: Fire TV
  host: 192.168.1.103
  adbkey: "/config/firetv_keys/adbkey"

- platform: kodi
  host: !secret shield_tv_host
  port: !secret kodi_port
  name: Kodi
  username: !secret kodi_user
  password: !secret kodi_pw
  enable_websocket: true
  timeout: 10
  turn_on_action:
  - service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: activate
  turn_off_action:
  - service: media_player.media_stop
    data:
      entity_id: media_player.kodi
  - service: media_player.kodi_call_method
    data:
      entity_id: media_player.kodi
      method: Addons.ExecuteAddon
      addonid: script.json-cec
      params:
        command: standby


- platform: denonavr
  host: 192.168.1.185
  name: Home cinema
  show_all_sources: false


- platform: universal
  name: Kodi TV
  state_template: >
    {% if (states.media_player.kodi.state == 'idle') and (states.input_boolean.kodi_tv_state.state == 'off') %}
    off
    {% else %}
    {{ states.media_player.kodi.state }}
    {% endif %}
  children:
    - media_player.kodi
    - media_player.home_cinema
  commands:
    turn_on:
      service: media_player.turn_on
      data:
        entity_id: media_player.kodi
    turn_off:
      service: media_player.turn_off
      data:
        entity_id: media_player.kodi
#    volume_set:
#      service: media_player.volume_set
#      data_template:
#        entity_id: media_player.kodi
#        volume_level: '{{ volume_level }}'
    volume_up:
      service: media_player.volume_up
      data:
        entity_id: media_player.home_cinema
    volume_down:
      service: media_player.volume_down
      data:
        entity_id: media_player.home_cinema
    volume_mute:
      service: media_player.volume_mute
      data:
        entity_id: media_player.home_cinema
#    select_source:
#      service: media_player.select_source
#      data_template:
#        entity_id: media_player.kodi
#        source: '{{ source }}'
  attributes:
    is_volume_muted: media_player.home_cinema|is_volume_muted
    volume_level: media_player.home_cinema|volume_level
#    source: media_player.kodi|source
#    source_list: media_player.kodi|source_list

sensor:
- platform: history_stats
  name: Horas de TV
  entity_id: media_player.kodi
  state: 'playing'
  type: time
  start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
  end: '{{ now() }}'


input_text:
  q_youtube:
    name: 'YouTube search:'
    initial: ''

input_select:
  kodi_results:
    name: Kodi API results
    options:
     - Nada que hacer
  youtube_videos:
    name: Youtube results
    options:
     - Nada que hacer
  tv_source:
    name: TV Source
    options:
     - Nada
     - Youtube
     - Kodi
     - VLC
     - Prime Video
     - Movistar+
     - RTVE a la carta
     - TDT
     - Kodi RPI
     - Inmersión
     - OFF
    initial: Nada
    icon: mdi:television-box

