# lovelace map:
#
#type: 'custom:xiaomi-vacuum-map-card'
#entity: vacuum.robot_aspirador
#map_image: /local/img/vacuum_floorplan_map.jpg
#calibration_points:
#  - vacuum:
#      x: 26000
#      'y': 25000
#    map:
#      x: 171
#      'y': 513
#  - vacuum:
#      x: 29800
#      'y': 29100
#    map:
#      x: 446
#      'y': 215
#  - vacuum:
#      x: 35500
#      'y': 30500
#    map:
#      x: 864
#      'y': 111
## default_mode: go_to_target, zoned_cleanup
#default_mode: predefined_zones
#zones:
## Office
#  - - - 25500
#      - 29000
#      - 28700
#      - 31500
## Dormitorio
#  - - - 34000
#      - 28700
#      - 37400
#      - 31300
#    - - 30600
#      - 28700
#      - 34000
#      - 29700
## Baño interior
#  - - - 31200
#      - 29800
#      - 33300
#      - 31400
## Cocina
#  - - - 23900
#      - 24300
#      - 29300
#      - 25900
## Salón
#  - - - 31200
#      - 24100
#      - 36500
#      - 28100
## Baño común
#  - - - 29600
#      - 29700
#      - 31100
#      - 31400
## Estudio
#  - - - 25400
#      - 26200
#      - 29200
#      - 28500
## Pasillo
#  - - - 29500
#      - 26100
#      - 30500
#      - 29600
## Hall
#  - - - 29400
#      - 24400
#      - 31000
#      - 25800
## Mesa centro
#  - - - 33500
#      - 24300
#      - 36200
#      - 26500

# No need for the python script now:
#  INPUT_SELECT = 'input_select.vacuum_clean_combination'
#  VACUUM_ENTITY = 'vacuum.robot_aspirador'
#
#  make_the_call = True
#  room_selection = data.get("room")
#  call_kwargs = {"entity_id": VACUUM_ENTITY, "command": "app_zoned_clean"}
#
#  if room_selection == 'Cocina':
#      call_kwargs["params"] = [[23900, 24300, 29300, 25900, 2]]
#  elif room_selection == 'Cocina y salón':
#      call_kwargs["params"] = [[23900, 24300, 29300, 25900, 1], [29300, 24300, 31200, 26000, 1], [31200, 24000, 36500, 28100, 1]]
#  elif room_selection == 'Salón':
#      call_kwargs["params"] = [[31200, 24000, 36500, 28100, 2]]
#  elif room_selection == 'Mesa de centro':
#      call_kwargs["params"] = [[33700, 24000, 36700, 26500, 2]]
#  elif room_selection == 'Zonas interiores':
#      # Estudio + Pasillo + Baño 2 + *Pasillo dorm* + Baño dorm + dorm
#      call_kwargs["params"] = [[25300, 26000, 29500, 28750, 1], [29600, 26000, 30600, 29800, 1], [29600, 29700, 31100, 31400, 1], [31200, 28500, 37600, 31400, 1]]
#  elif room_selection == 'Zona office':
#      call_kwargs["params"] = [[25500, 29000, 29500, 31800, 2]]
#  elif room_selection == 'Zona dormitorio y baño':
#      call_kwargs["params"] = [[34000, 28500, 37600, 31500, 2], [31200, 29800, 33300, 31400, 1]]
#  elif room_selection == 'Ir al salón':
#      call_kwargs["command"] = "app_goto_target"
#      call_kwargs["params"] = [33700, 26500]
#  elif room_selection == 'Ir al distribuidor':
#      call_kwargs["command"] = "app_goto_target"
#      call_kwargs["params"] = [29800, 29100]
#  elif room_selection == 'Nada':
#      # logger.info("No Cleaning of zone %s", room_selection)
#      make_the_call = False
#  else:
#      logger.error("ROOM not recognized: %s", room_selection)
#      make_the_call = False
#
#  if make_the_call:
#      hass.services.call('vacuum', 'send_command', call_kwargs)
#      logger.warning("Cleaning ZONE %s: %s", room_selection,
#                     str(call_kwargs['params']))

homeassistant:
  customize:
    vacuum.robot_aspirador:
      friendly_name: Aspiradora

vacuum:
- platform: xiaomi_miio
  name: robot_aspirador
  host: !secret xiaomi_vacuum_robot_ip
  token: !secret xiaomi_vacuum_robot_token
  scan_interval: 120
