homeassistant:
  customize:
    vacuum.robot_aspirador:
      friendly_name: Aspiradora

vacuum:
- platform: xiaomi_miio
  name: robot_aspirador
  host: !secret xiaomi_vacuum_robot_ip
  token: !secret xiaomi_vacuum_robot_token
  scan_interval: 120

input_select:
  vacuum_clean_combination:
    name: Selección de zona de aspirado
    options:
     - Nada
     - Cocina
     - Cocina y salón
     - Salón
     - Ir al salón
     - Mesa de centro
     - Ir al distribuidor
     - Zonas interiores
     - Zona office
     - Zona dormitorio y baño
    initial: Nada
    icon: mdi:robot-vacuum
