###############################################################################
# YEELIGHT strip
###############################################################################
homeassistant:
  customize:
#    light.tira_tv:
    light.yeelight_strip_7811dca21ecf:
      icon: mdi:dots-horizontal
      homebridge_name: Tira TV
      friendly_name: Tira TV
    light.yeelight_strip_7811dca21ecf_2:
      homebridge_hidden: true
      hidden: true

light:
  - platform: yeelight
    devices:
      192.168.1.46:
#        name: Tira TV
        name: yeelight_strip_7811dca21ecf
        transition: 1000
        use_music_mode: True #(defaults to False)
#        save_on_change: False #(defaults to True)

