###############################################################################
# YEELIGHT strip
###############################################################################
homeassistant:
  customize:
#    light.tira_tv:
    light.yeelight_strip_7811dca21ecf:
      icon: mdi:dots-horizontal
      homebridge_name: Tira TV
      friendly_name: Tira TV
#      homebridge_switch_type: outlet

#light:
#  - platform: yeelight
#    devices:
#      192.168.1.46:
#        name: Tira TV
#        transition: 1000
#        use_music_mode: True #(defaults to False)
##        save_on_change: False #(defaults to True)
#
light:
  - platform: yeelight
    devices:
      192.168.1.46:
        name: yeelight_strip_7811dca21ecf
        transition: 1000
        use_music_mode: True #(defaults to False)
#        save_on_change: False #(defaults to True)

