homeassistant:
  name: Domus
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
  packages:  !include_dir_named packages
  customize: !include customize.yaml
  whitelist_external_dirs:
    - !secret ext_dir_1
    - !secret ext_dir_2
#    - !secret ext_dir_3
  #customize_glob: !include frontend/customize_glob.yaml

frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/state-card-floorplan.html
    - /local/custom_ui/floorplan/ha-floorplan.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-floorplan.html
    - /local/custom_ui/floorplan/ha-floorplan.htmll
  themes: !include_dir_merge_named themes


config:
http:
  base_url: !secret base_url
  api_password: !secret hass_pw
  ip_ban_enabled: True
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24
    - 172.30.33.2
    - 172.30.32.2
#  use_x_forwarded_for: True
#    trusted_proxies:
#      - 127.0.0.1
#      - ::1
#    trusted_networks:
#      - 127.0.0.1
#      - ::1
#      - 192.168.0.0/24
#      - fd00::/8
#  use_x_forwarded_for: False
#  trusted_proxies:
logger:
  default: warn
  logs:
    aiohttp.server: critical
    custom_components.switch.tuyawifiplug: error
    miio: critical
    homeassistant.bootstrap: info
    homeassistant.core: error
    homeassistant.setup: warning
    homeassistant.components.automation: info
    homeassistant.components.floorplan: debug
    homeassistant.components.history: info
    homeassistant.components.http.auth: error
    homeassistant.components.media_player: info
    homeassistant.components.light.yeelight: critical
    homeassistant.components.python_script: warning
    homeassistant.components.recorder: info
    homeassistant.components.script: info
    homeassistant.components.sensor.influxdb: error
    homeassistant.components.tts: debug
    homeassistant.components.vacuum.xiaomi_miio: critical
    homeassistant.helpers.entity: error

mqtt:
##  discovery: true
##  discovery_prefix: homeassistant
##  broker: core-mosquitto
#  broker: 192.168.1.30
  broker: 192.168.1.10
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1
  birth_message:
    topic: 'hass/status_master'
    payload: 'on'
    qos: !secret mqtt_default_qos
  will_message:
    topic: 'hass/status_master'
    payload: 'off'
    qos: !secret mqtt_default_qos

updater:
  include_used_components: true

hassio:
discovery:
#  enable:
#    - homekit

conversation:
python_script:

# Text to speech
tts:
  platform: google
  language: 'es'

history:
  include:
    domains:
      - sun
      - binary_sensor
      - sensor
      - media_player
      - device_tracker
      - light
      - switch
      - vacuum
logbook:
  include:
    domains:
      - sun
      - automation
      - light
      - switch
      - media_player
      - vacuum
      - script
      - python_script
      - input_boolean

influxdb:
  host: !secret influxdb_host
  port: !secret influxdb_port
  database: !secret influxdb_db
  username: !secret influxdb_user
  password: !secret influxdb_pass
  # ssl: true
  # verify_ssl: true
  default_measurement: state

recorder:
  purge_interval: 1
  purge_keep_days: !secret recorder_purge_days
  db_url: !secret recorder_db_url

system_health:

panel_iframe:
  contab_access:
    title: Contabilidad
    url: !secret weblink_contab_url
    icon: mdi:bank
  grafana_access:
    title: Grafana
    url: !secret grafana_url
    icon: mdi:chart-areaspline
#  psychrochart:
#    title: Psicrométrico
#    url: !secret psychrocam_svgchart_url
#    icon: mdi:gradient

#group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
weblink: !include weblinks.yaml
scene: !include scenes.yaml

person:
  - name: Eugenio
    id: !secret person_id_eu
    user_id: !secret user_id_eu
    device_trackers:
      - device_tracker.iphone_bt
      - device_tracker.iphone
      - device_tracker.homeadmin_iphone
      - device_tracker.applewatch

  - name: Carmen
    id: !secret person_id_carmen
    user_id: !secret user_id_carmen
    device_trackers:
      - device_tracker.iphone_de_carmen_bt
      - device_tracker.iphone_se
      - device_tracker.iphonese
      - device_tracker.homeadmin_iphonese
      - device_tracker.applewatch_carmen
