Salón:
  name: Luces salón
#  control: hidden
  entities:
    - input_number.light_main_slider_salon
    - input_number.light_temp_slider_salon
    - input_select.salon_light_scene
    - light.bola_grande
    - light.bola_pequena
    - light.central
    - light.pie_tv
    - light.pie_sofa
    - light.cuenco
    - light.lamparita
    - light.go
    - light.tira

#Estudio:
##  entities:
##    control: hidden
#    - light.flexo
##    - switch.estudio_light_relay

control_dormitorio:
  name: Luces dormitorio
#  control: hidden
  entities:
    - light.aura_habitacion
    - light.hue_habitacion

#  Hue sensors:
#    - sensor.hue_dimmer_switch
#    - sensor.iphone

sensors_dormitorio:
  name: Dormitorio
  control: hidden
  entities:
    - sensor.dormitorio_temperature_rpi2mpd
    - sensor.dormitorio_humidity_rpi2mpd
    - sensor.dormitorio_pressure_rpi2mpd
    - sensor.dormitorio_htu21d_temperature_rpi2mpd
    - sensor.dormitorio_htu21d_humidity_rpi2mpd
    - sensor.dormitorio_light_level_rpi2mpd
    - binary_sensor.pir_dormitorio_rpi2mpd

Despertador:
  control: hidden
  entities:
    - switch.alarm_clock_status
  #  - input_boolean.alarm_clock_status
    - input_number.alarm_clock_hour
    - input_number.alarm_clock_minute
    - sensor.alarm_clock_time
    - input_select.room_altavoces
    # From rf outlets:
#    - switch.altavoz
    - input_boolean.manual_trigger_lacafetera

Enchufes:
  control: hidden
  entities:
    - switch.bomba_circ_acs
    - switch.calentador
    - switch.camara
    - switch.altavoz
    - switch.office_floor

    - switch.cocina
    - switch.calefactor
    - switch.new_switch_2
    - switch.new_switch_3

#Terraza:
#  - light.terraza

Consumo eléctrico:
  - sensor.enerpi_power
  - sensor.enerpi_ch1
  - sensor.enerpi_ch2
  - binary_sensor.electricity_high_cost_interval
#  - sensor.enerpi_ldr

Kodi:
  control: hidden
  entities:
    - switch.toggle_kodi_ambilight
    - switch.toggle_config_kodi_ambilight
    - script.play_kodi_pvr
    - script.stop_kodi
    - script.update_library
    - script.quit_kodi
    - script.restart_kodi_osmc

Media select:
  control: hidden
  entities:
    - script.recent_episodes
    - script.recent_movies
    - script.pvr_channels
    - input_select.kodi_results
    - input_text.q_youtube
    - input_select.youtube_videos

Local:
  - sensor.local_htu21d_temperature
  - sensor.local_htu21d_humidity
  - sensor.local_light_level
  - binary_sensor.local_pir

LocalHost:
  - sensor.hass_cpu_temperature
  - sensor.cpu_used
  - sensor.ram_available
  - sensor.disk_used_
  - sensor.last_boot

Host Dormitorio:
  - sensor.hass_cpu_temperature_rpi2mpd
  - sensor.cpu_used_rpi2mpd
  - sensor.ram_available_rpi2mpd
  - sensor.disk_used__rpi2mpd
  - sensor.last_boot_rpi2mpd

Resto de hosts:
  - sensor.enerpi_cpu_temperature
  - sensor.kodi_cpu_temperature

Eugenio:
  - device_tracker.iphone_bt
  - device_tracker.iphone
  - device_tracker.homeadmin_iphone

Carmen:
  - device_tracker.iphone_de_carmen_bt
  - device_tracker.iphone_se
  - device_tracker.iphonese
  - device_tracker.homeadmin_iphonese

Family:
  - group.eugenio
  - group.carmen

esp_livingroom:
  name: Salón
  control: hidden
  entities:
    - sensor.sensor_livingroom_temperature
    - sensor.sensor_livingroom_humidity
    - sensor.sensor_livingroom_pressure
    - sensor.sensor_livingroom_illumination
#    light.sensor_livingroom__rgblight
    - binary_sensor.sensor_livingroom_mov1
#    - binary_sensor.sensor_livingroom_online
    - sensor.sensor_livingroom__snum

esp_office:
  name: Estudio
  control: hidden
  entities:
    - sensor.sensor_office_temperature
    - sensor.sensor_office_humidity
#      - sensor.sensor_office_pressure
    - sensor.sensor_office_illumination
    - sensor.sensor_office_adc1
    - sensor.sensor_office_adc2
#    light.sensor_office__rgblight
#    #switch.sensor_office__switch_led
#    light.sensor_office__switch_led
    - binary_sensor.sensor_office_mov1
#    - binary_sensor.sensor_office_online
    - sensor.sensor_office__snum

esp_terraza:
  name: Terraza
#    control: hidden
  entities:
    - light.terraza
    - sensor.sensor_terraza_temperature
    - sensor.sensor_terraza_humidity
    - sensor.sensor_terraza_pressure
    - sensor.sensor_terraza_illumination
    - binary_sensor.sensor_terraza_mov1
#    - binary_sensor.sensor_terraza_online
    - sensor.sensor_terraza__snum

esp_galeria:
  name: Galería
#    control: hidden
  entities:
#      - light.galeria
    - sensor.sensor_galeria_temperature
    - sensor.sensor_galeria_humidity
#      - sensor.sensor_galeria_pressure
#      - sensor.sensor_galeria_illumination
    - switch.calentador
    - switch.bomba_circ_acs
    - sensor.sensor_acs_probe_1
    - sensor.sensor_acs_probe_2
    - sensor.sensor_acs_probe_3
    - sensor.sensor_acs_probe_4
    - sensor.sensor_acs_probe_5
    - sensor.sensor_acs_probe_6
#      - binary_sensor.sensor_galeria_mov1
#    - binary_sensor.sensor_galeria_online
    - sensor.sensor_galeria__snum

Conectivity:
  - binary_sensor.services_notok
  - sensor.ip_externa
  - binary_sensor.router_on
  - binary_sensor.dormitorio_online
#  - binary_sensor.estudio_online
  - binary_sensor.sensor_livingroom_online
  - binary_sensor.sensor_office_online
  - binary_sensor.sensor_terraza_online
  - binary_sensor.sensor_galeria_online
  - binary_sensor.enerpi_online
#  - binary_sensor.cocina_online
  - binary_sensor.database_ok
  - binary_sensor.internet_online
  - binary_sensor.nas_online
  - binary_sensor.pushbullet_online
  - binary_sensor.email_online
  - binary_sensor.telegram_online
  - binary_sensor.ios_online
  - binary_sensor.kodi_online
  - sensor.uptime
  - sensor.ssl_certificate_expiry
  - sensor.error_counter_notifiers
  - sensor.core_error_counter
  - sensor.warning_counter_core
  - sensor.telegram_default_chatid
#  - sensor.sensor_livingroom__snum
#  - sensor.sensor_office__snum
#  - sensor.sensor_terraza__snum
#  - sensor.sensor_galeria__snum

general_config:
  name: General
  control: hidden
  entities:
    - binary_sensor.workday_sensor
    - sun.sun
    - input_boolean.switch_motion_lights
    - input_number.light_duration_after_motion
    - input_boolean.switch_control_enerpi_max_power
    - input_number.enerpi_max_power
    - input_number.enerpi_max_power_reset
    - script.good_night

dt_imac:
#  hidden: true
  name: iMac
  entities:
    - device_tracker.imac
    - device_tracker.imac_wifi
    - device_tracker.imac_bt

dt_mbp:
  name: MacBook Pro
#  hidden: true
  entities:
    - device_tracker.macbook_pro
    - device_tracker.macbook_pro_bt

dt_ipad:
  name: iPad
#  hidden: true
  entities:
    - device_tracker.ipad
    - device_tracker.ipad_wifi

Dispositivos:
  control: hidden
  entities:
    - group.dt_imac
    - group.dt_mbp
    - group.dt_ipad
    - device_tracker.applewatch
    - device_tracker.applewatch_carmen
    - input_boolean.eu_presence
    - input_boolean.carmen_presence
    #  - device_tracker.imac
    #  - device_tracker.imac_wifi
    #  - device_tracker.imac_bt
    #  - device_tracker.macbook_pro
    #  - device_tracker.iphone_bt
    #  - device_tracker.iphone
    #  - device_tracker.homeadmin_iphone
    #  - sensor.iphone_battery_state
    #  - sensor.iphone_battery_level

    #  - device_tracker.iphone_de_carmen_bt
    #  - device_tracker.iphone_se
    #  - device_tracker.homeadmin_iphone_se

    #  - device_tracker.ipad
    #  - device_tracker.ipad_wifi
    #  - sensor.ipad_de_eugenio_battery_level
    #  - sensor.ipad_de_eugenio_battery_state
    - device_tracker.nas_qnap
    - device_tracker.nas_syno
    - device_tracker.hue_bridge
    - device_tracker.rpi3_enerpi
    - device_tracker.rpi3_osmc
    - device_tracker.rpi2_bedroom
    - device_tracker.b827ebcaec07
    - device_tracker.b827ebee3f3b
    - device_tracker.xiaomi_router
    - device_tracker.xiaomi_vacuum
    - device_tracker.jo01
    - device_tracker.airport_express_a
    - device_tracker.qnap_ubuntu
    - device_tracker.router_movistar
    - device_tracker.deco_movistar
    - device_tracker.camera_sricam360

Dev boards:
  control: hidden
  entities:
    - device_tracker.30aea4060680
    - device_tracker.240ac48163f8
    - device_tracker.240ac48124a4
    - device_tracker.30aea4001d1c
    - device_tracker.240ac4817724
    - device_tracker.00e04c534458
    - device_tracker.240ac4817974


Baterías:
  - sensor.iphone_battery_state
  - sensor.iphone_battery_level
  - sensor.bateria_iphone_x
  - sensor.iphone_de_maria_del_carmen_battery_state
  - sensor.iphone_de_maria_del_carmen_battery_level
  - sensor.bateria_iphone_se
  - sensor.ipad_de_eugenio_battery_state
  - sensor.ipad_de_eugenio_battery_level

#ESP Galería:
#  - binary_sensor.sensorgaleria_online
#  - sensor.sensorgaleria_adc1
#  - sensor.sensorgaleria_adc2
#  - sensor.sensorgaleria_snum
#  - light.sensorgaleria_switch_led
#  - light.sensorgaleria_rgblight
#
#Plancha:
#  - sensor.sensor_spk_1t
#  - sensor.sensor_spk_1h
#  - sensor.sensor_spk_1p
#  - sensor.sensor_spk_1i
#  - binary_sensor.sensor_spk_1_mov1
#
#ESP Plancha:
#  - binary_sensor.sensor_spk_1_online
#  - sensor.sensor_spk_1_snum
#  - light.sensor_spk_1_switch_led
  
# ESP WROOM32:
#   - binary_sensor.sensorwroom32_1_online
#   - sensor.sensorwroom32_1t
#   - sensor.sensorwroom32_1h
#   - sensor.sensorwroom32_1p
#   - sensor.sensorwroom32_1i
#   - sensor.sensorwroom32_1_snum
#   - light.sensorwroom32_1_switch_led
  
Pi Hole:
  - sensor.pihole_ads_blocked_today
  - sensor.pihole_ads_percentage_blocked_today
  - sensor.pihole_dns_queries_today
  - sensor.pihole_dns_unique_clients
  - sensor.pihole_dns_unique_domains
#  - sensor.pihole_domains_blocked


weather_dark_sky_now:
  name: Ahora
  entities:
    - sensor.dark_sky_summary
    - sensor.dark_sky_temperature
    - sensor.dark_sky_apparent_temperature
    - sensor.dark_sky_dew_point

    - sensor.dark_sky_humidity
    - sensor.dark_sky_pressure

weather_dark_sky_today:
  name: Hoy
  entities:
    - sensor.dark_sky_hourly_summary
    - sensor.dark_sky_daily_high_apparent_temperature
    - sensor.dark_sky_daily_high_temperature
    - sensor.dark_sky_daily_low_temperature

weather_dark_sky_tomorrow:
  name: Mañana
  entities:
    - camera.weather_svg
    - sensor.dark_sky_daily_summary

    - sensor.dark_sky_temperature_1
    - sensor.dark_sky_apparent_temperature_1
    - sensor.dark_sky_dew_point_1
    - sensor.dark_sky_humidity_1
    - sensor.dark_sky_pressure_1

    - sensor.dark_sky_daily_high_apparent_temperature_1
    - sensor.dark_sky_daily_high_temperature_1
    - sensor.dark_sky_daily_low_temperature_1

weather_dark_sky_aftertomorrow:
  name: Pasado mañana
  entities:
    - sensor.dark_sky_temperature_2
    - sensor.dark_sky_apparent_temperature_2
    - sensor.dark_sky_dew_point_2
    - sensor.dark_sky_humidity_2
    - sensor.dark_sky_pressure_2

    - sensor.dark_sky_daily_high_apparent_temperature_2
    - sensor.dark_sky_daily_high_temperature_2
    - sensor.dark_sky_daily_low_temperature_2

weather_dark_sky_afterthree:
  name: En tres dias
  entities:
    - sensor.dark_sky_temperature_3
    - sensor.dark_sky_apparent_temperature_3
    - sensor.dark_sky_dew_point_3
    - sensor.dark_sky_humidity_3
    - sensor.dark_sky_pressure_3

    - sensor.dark_sky_daily_high_apparent_temperature_3
    - sensor.dark_sky_daily_high_temperature_3
    - sensor.dark_sky_daily_low_temperature_3

Links:
  - weblink.grafana
  - weblink.nas_qnap
  - weblink.nas_synology
  - weblink.contabilidad
  - weblink.hassio_lan
  - weblink.hassio_pihole
  - weblink.slave_hass
  - weblink.slave_hass_mpd
  - weblink.enerpi
  - weblink.motioneye
  - weblink.kodi_web_interface
  - weblink.tv_headend
  - weblink.mopidy
  - weblink.router_movistar

Red e Internet:
  - sensor.speedtest_ping
  - sensor.speedtest_download
  - sensor.speedtest_upload

Automatizaciones:
  control: hidden
  entities:
    - automation.buenas_noches
    - automation.encendido_de_tv_si_apagada_y_kodi_play
    - automation.apagado_de_tv_si_encendida_y_kodi_en_idle__10_min
    - automation.encendido_automatico_de_cam_salon
    - automation.apagado_de_cam_salon_en_kodi_play_nocturno
    - automation.encendido_luces_dormitorio
    - automation.salon_select_scene
    - automation.brillo_salon
    - automation.tono_salon
    - automation.notify_sunset
    - automation.new_bt_device_notifier
    - automation.update_notifications
    - automation.start_homeassistant

# ----------------------------------------------------------------------------------------------------------------------
# VIEWS
# ----------------------------------------------------------------------------------------------------------------------

Status:
  name: Home Status
  icon: mdi:castle
  view: yes
  entities:
    - group.consumo_electrico
    - group.salon
    - group.esp_livingroom
    - group.control_dormitorio
    - group.sensors_dormitorio
#    - group.estudio
    - group.esp_office
#    - group.terraza
    - group.esp_terraza
    - group.esp_galeria
    - group.local
    # - group.salon
    # - group.salon_simple
    # - group.cocina
    # - group.cocina_simple
#    - group.camaras

Control:
  name: Home Control
  icon: mdi:auto-fix
  view: yes
  entities:
    - group.salon
    - group.control_dormitorio
    - group.terraza
    - group.estudio
    - vacuum.robot_aspirador
    - group.all_lights
    - group.enchufes
    # - group.master_luces_del_salon
    # - group.luces_salon
    # - group.luces_dormitorio
    # - group.luces_estudio
    # - group.enchufes
    # - media_player.kodi_tv
    # - group.kodi
    # - media_player.dormitorio_mopidy
    # - group.xiaomi_vacuum_robot
#    - group.despertador

# Alarm Panel:
#   name: Alarm configuration
#   icon: mdi:shield-outline
#   view: yes
#   entities:
#     - group.alarma
#     - group.inputs_alarm
#     - group.camaras
#     - group.alarm_control
kodi_control:
  name: Kodi
  icon: mdi:kodi
  view: yes
  entities:
    - media_player.kodi_tv
    - group.kodi
    - group.media_select

current_meter_control:
  name: Consumos
  view: yes
  icon: mdi:flash
  entities:
    - group.consumo_electrico
    - camera.consumo_7d
    - camera.electricidad_24h
    - switch.bomba_circ_acs
    - switch.calentador

alarm_clock:
  name: Despertador
  view: yes
  icon: mdi:alarm
  entities:
    - group.despertador
    - media_player.dormitorio_mopidy
    - media_player.kodi_tv

Weather:
  name: El tiempo
  icon: mdi:weather-partlycloudy
  view: yes
  entities:
    - weather.local_weather
    - camera.weather_svg
    - camera.webcam_playa_1
    - camera.webcam_playa_2
    - camera.webcam_playa_3
    - group.aislamiento
    - group.weather_dark_sky_now
    - group.weather_dark_sky_today
    - group.weather_dark_sky_tomorrow
    - group.weather_dark_sky_aftertomorrow
    - group.weather_dark_sky_afterthree
    - group.weather_forecast
    - group.weather

Home Network:
  name: Red local
  view: yes
  icon: mdi:sitemap
  entities:
    - camera.sricam_360
    - group.family
    - group.dispositivos
    - group.localhost
    - group.host_dormitorio
    - group.resto_de_hosts
    - group.links
#    - group.esp_galeria
#    - group.esp_plancha
#    - group.esp_wroom32
    - group.dev_boards
    - group.baterias

    #- group.red_e_internet

Master conf:
  name: Master configuration
  icon: mdi:settings
  view: yes
  entities:
    - group.hass_control
    - group.conectivity
    - group.general_config
    - group.pi_hole
#      - binary_sensor.estudio_manual_light_switch_rpi2h
#      - sensor.hue_dimmer_switch
#      - input_number.max_humidity
#      - automation.encendido_luces_estudio
#      - automation.apagado_luces_estudio
#      - automation.apagado_de_climatizador_evaporativo
    - group.red_e_internet
    - group.automatizaciones
    - group.all_scripts
