# Testing scenes...
- name: La caja tonta
  entities:
    script.play_kodi_pvr: on

- name: Modo series
  entities:
    script.start_tvshows_mode: on

- name: Golpe de frío
  entities:
    script.quick_cool_session: on

- name: Golpe de calor
  entities:
    script.quick_heat_session: on

#- name: Cuenco red
#  entities:
#    light.cuenco:
#      state: on
#      transition: 1
#      brightness: 100
#      rgb_color: [255, 0, 0]
#
#- name: Cuenco blue
#  entities:
#    light.cuenco:
#      state: on
#      transition: 1
#      brightness: 100
#      rgb_color: [0, 0, 255]