good_night:
  alias: Buenas noches
#  id: good_night
  sequence:
    - alias: Apagado de TV, Ambilight, Cocina, Estudio, Calefactor e impresora
      service: switch.turn_off
#      entity_id: switch.kodi_tv_salon,switch.toggle_kodi_ambilight,switch.caldera,switch.altavoz,switch.cocina,switch.calefactor,switch.estudio_light_relay,switch.impresora
      entity_id: switch.kodi_tv_salon,switch.toggle_kodi_ambilight,switch.cocina

    - alias: Encendido de CAM Salón
      service: switch.turn_on
      entity_id: switch.camara

    - alias: Notificación de buenas noches
      service: telegram_bot.send_message
      data_template:
        title: '*¡Buenas noches!*'
        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
        message: 'Script de buenas noches *auto-activado*. Apagado de interruptores y encendido de cámaras de seguridad.'
        disable_notification: true

    - delay:
        seconds: 10

    - alias: Apagado de luces
      service: light.turn_off
#      entity_id: light.salon,light.dormitorio,light.estudio,light.exterior

play_kodi_pvr:
#  id: play_kodi_pvr:
  alias: Enciende la caja tonta
  sequence:
    - alias: TV on
      service: media_player.turn_on
      data:
        entity_id: media_player.kodi

    - alias: Play TV channel
      service: media_player.play_media
      data_template:
        entity_id: media_player.kodi
  #      The type of the content to play. Must be one of MUSIC, TVSHOW, VIDEO, EPISODE, CHANNEL or PLAYLIST
        media_content_type: "CHANNEL"
        media_content_id: >
          {% if (now().hour < 14) or ((now().hour == 14) and (now().minute < 50)) %}
            10
          {% elif (now().hour < 16) %}
            15
          {% elif (now().hour < 20) %}
            2
          {% elif (now().hour == 20) and (now().minute < 50) %}
            10
          {% elif (now().hour == 20) or ((now().hour == 21) and (now().minute < 15)) %}
            15
          {% else %}
            10
          {% endif %}

    - alias: Notificación de selección de canal
      service: telegram_bot.send_message
      data_template:
        title: '*TV PVR ON*'
        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
        disable_notification: true
        message: >
          Encendido de caja tonta en canal '{% if (now().hour < 14) or ((now().hour == 14) and (now().minute < 50)) %}laSexta HD{% elif (now().hour < 16) %}antena3 HD{% elif (now().hour < 20) %}24h{% elif (now().hour == 20) and (now().minute < 50) %}laSexta HD{% elif (now().hour == 20) or ((now().hour == 21) and (now().minute < 15)) %}antena3 HD{% else %}laSexta HD{% endif %}'.
        inline_keyboard:
          - OFF:/service_call media_player.turn_off media_player.kodi, ON:/service_call media_player.turn_on media_player.kodi, ‖:/service_call media_player.media_play_pause media_player.kodi, ◼︎:/service_call media_player.media_stop media_player.kodi

restart_kodi_osmc:
  alias: Restart KODI OSMC
  sequence:
    - service: notify.ios_iphone
      data:
        title: 'Reiniciando KODI OSMC'
        message: "KODI debería 'morir' y 'resucitar' en unos segundos"
        data:
          push:
            category: "CONFIRM"
    - service: telegram_bot.send_message
      data_template:
        title: 'Reiniciando KODI OSMC'
        target: '{{ states.sensor.telegram_default_chatid.state | int }}'
        message: "KODI debería 'morir' y 'resucitar' en unos segundos"
        disable_notification: true
    - service: shell_command.cmd_kill_kodi

stop_kodi:
  alias: Stop playback in Kodi
  sequence:
      service: media_player.media_stop
      data:
        entity_id: media_player.kodi

quit_kodi:
  alias: Quit Kodi
  sequence:
    service: media_player.kodi_call_method
    data:
      method: Application.Quit

update_library:
  alias: Update Kodi Library
  sequence:
    - alias: Call Kodi update
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: VideoLibrary.Scan

recent_movies:
  alias: Últimas películas
  sequence:
    - alias: Call Kodi serv
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: VideoLibrary.GetRecentlyAddedMovies
        properties:
          - title
          - year
          - file
          - lastplayed

recent_episodes:
  alias: Últimos episodios
  sequence:
    - alias: Call Kodi serv
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: VideoLibrary.GetRecentlyAddedEpisodes
        properties:
          - showtitle
          - file
          - lastplayed
          - dateadded
          - firstaired

pvr_channels:
  alias: Canales de TV
  sequence:
    - alias: Call Kodi serv
      service: media_player.kodi_call_method
      data:
        entity_id: media_player.kodi
        method: PVR.GetChannels
        channelgroupid: 1