# travis_secrets.yaml
name: Test
hass_pw: secret
country_code: ES
province_code: CVA
time_zone: Europe/Madrid
weather_location: secret
latitude: 00.00000
longitude: 00.00000
elevation: 0
radius_home: 1
z1_name: z1
z1_latitude: 00.00000
z1_longitude: 00.00000
z1_radius: 1
z1_icon: mdi:icon
z2_name: z2
z2_latitude: 00.00000
z2_longitude: 00.00000
z2_radius: 1
z2_icon: mdi:icon

base_url: https://secret.com
base_host: 'secret.com'
local_ip: 192.168.200.200
external_ip: 233.233.233.233
ext_dir_1: /
ext_dir_2: /usr
ext_dir_3: /usr/bin
ext_dir_4: /home/travis/build/azogue/hassio_config

no_ip_user: user_noip
no_ip_password: 123455
recorder_db_url: mysql://homeassistant:123455@localhost/hassdb
recorder_flush_cmd: "CMD"
msg_recorder_flush: "MSG"
recorder_purge_days: 14
hue_bridge_lan_ip: 192.168.1.45

influxdb_host: 192.168.200.204
influxdb_port: 8086
influxdb_db: hass
influxdb_user: hass
influxdb_pass: yeha62hd
ssh_cmd_rpi_temp_influxdb: ssh pi@192.168.200.204 cat /sys/class/thermal/thermal_zone0/temp

grafana_url: https://secret.com/grafana_app/dashboard/db/dashb?refresh=1m&orgId=1&from=now-24h&to=now&theme=light
grafana_elec_url: https://secret.com/grafana_app/dashboard/db/enerpi?refresh=1m&orgId=1&from=now-7d&to=now
grafana_api_key: 3rfoq3ifjasesjwj2idiasfii
grafana_api_user: user_gr
grafana_db_elec_consumo_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{% set ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/vistazo?refresh=1h&orgId=1&panelId=4&from={{ ((ts_hour - (7*24+1)*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0) }}&width=1000&height=800&tz=CET'
grafana_db_elec_power_templ: '{% set ts_ahora = as_timestamp(now()) | round %}{% set ts_hour = ts_ahora + 3600 - ts_ahora % 3600 %}https://secret.com/grafana_app/render/dashboard-solo/db/para-ha-elec24h?refresh=1m&orgId=1&panelId=5&from={{ ((ts_hour - 24*3600) * 1000) | round }}&to={{ (ts_hour * 1000) | round(0) }}&width=1000&height=800&tz=CET'
grafana_username: user_gr
grafana_password: passwordforgrafanaaccess

#contab_url: https://secret.com/other/
weblink_contab_url: https://secret.com/contabilidad/
url_saas_torrent_search: https://secret.com/search
psychrocam_svgchart_url: https://secret.com/svgchart
psychrocam_ha_evo_url: https://secret.com/ha_evolution

# NAS QNAP:
nas_qnap_host: 192.168.200.20
nas_qnap_username: superadmin
nas_qnap_password: superadminpwd

# Wifi smart plugs
maxcio_wifi_plug_1_host: "192.168.200.73"
maxcio_wifi_plug_1_device_id: "localaccessdeviceid"
maxcio_wifi_plug_1_local_key: "localaccesskey"

myemail: my@email.com
email_target: my@email.com
hass_email: my@email.com
hass_email_pw: esjwj2idiasfii3rfoq3ifjas

pushbullet_api_key: esjwj2idiasfii3rfoq3ifjas
pb_target: email/my@email.com

icloud_user: my@email.com
icloud_pwd: esjwj2idiasfii3rfoq3ifjas

gcm_api_key: esjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjasesjwj2idiasfii3rfoq3ifjas
gcm_sender_id: 342424249766

ios_target: esjwj2idiasfii3rfoq3ifjas
ios_target_ipad: esjwj2idiasfii3rfoq3ifjas
ios_target_iphonese: esjwj2idiasfii3rfoq3ifjas

telegram_bot_api_key: esjwj2idiasfii3rfoq3ifjas
telegram_bot_chat_id_admin: 1234556
telegram_bot_chat_id_2: 9876354
telegram_bot_group: -9876354
telegram_bot_all_targets: 1234556,9876354
telegram_bot_chat_id_admin_name: N1
telegram_bot_chat_id_2_name: N2
telegram_bot_chat_id_3: 370408701
telegram_bot_chat_id_3_name: N3

xiaomi_vacuum_robot_token: '12345678901234567890123456789012'
xiaomi_vacuum_robot_ip: 192.168.200.229

openweathermap_api_key: onelongsecretkey
darksky_api_key: onelongsecretkey
weather_svg_cam_url: https://www.yr.no/place/country/state/city/meteogram.svg
weather_svg_cam_name: City
yahoo_woeid: 123445678

mac_nas: 00:00:00:00:00:00
nas_url: https://secret_other.com
weblink_nas_url: https://secret.com/index.cgi
weblink_nas_qnap_url: https://qlink.to/MYID
weblink_hassio_lan: http://192.168.200.200:8123/
weblink_pihole: http://192.168.200.203:8080/admin/index.php
weblink_tv_headend: http://192.168.200.201:9981/
weblink_kodi_web: http://192.168.200.201:8080/
pihole_host: 192.168.200.248:8080

mqtt_broker: 127.0.0.1
mqtt_port: 1883
mqtt_client_id: client_id
mqtt_username: usermq
mqtt_password: secretkey
mqtt_default_qos: 2
mqtt_default_retain: true
mqtt_default_expiration: 120

mqtt_topic_esp1_hum: "sensor/hum_esp1"
mqtt_topic_esp1_temp: "sensor/temp_esp1"
mqtt_topic_esp1_online: "control/online_esp1"
# enerPI MQTT - esp32 en cuadro: (v11.9, no ts)
mqtt_topic_esp32_ener_stream: custom_route/id_esp1/stream
mqtt_topic_esp32_ener_lwt: custom_route/id_esp1/lwt
mqtt_topic_esp32_ener_status: custom_route/id_esp1/status
mqtt_topic_esp32_ener_command: custom_route/id_esp1/command
# ESP Estudio (MQTT sensors)
mqtt_topic_esp_office_status: custom_route/id_esp2/status
mqtt_topic_esp_office_command: custom_route/id_esp2/command
mqtt_topic_esp_office_lwt: custom_route/id_esp2/lwt
# ESP Salón (MQTT sensors)
mqtt_topic_esp_livingroom_status: custom_route/id_esp3/status
mqtt_topic_esp_livingroom_command: custom_route/id_esp3/command
mqtt_topic_esp_livingroom_lwt: custom_route/id_esp3/lwt
# ESP Terraza (MQTT sensors)
mqtt_topic_esp_terraza_status: custom_route/id_esp4/status
mqtt_topic_esp_terraza_command: custom_route/id_esp4/command
mqtt_topic_esp_terraza_lwt: custom_route/id_esp4/lwt
# ESP Galería (MQTT sensors)
mqtt_topic_esp_acs_status: custom_route/id_esp5/status
mqtt_topic_esp_acs_command: custom_route/id_esp5/command
mqtt_topic_esp_acs_lwt: custom_route/id_esp5/lwt
# ESP Cocina (MQTT sensors)
mqtt_topic_esp_kitchen_status: custom_route/id_esp6/status
mqtt_topic_esp_kitchen_command: custom_route/id_esp6/command
mqtt_topic_esp_kitchen_lwt: custom_route/id_esp6/lwt
# ESP Persianas
mqtt_topic_esp_covers_command: "custom_route/id_esp7/command"
mqtt_topic_esp_covers_status: "custom_route/id_esp7/status"
mqtt_topic_esp_covers_lwt: "custom_route/id_esp7/lwt"
# ESP Baño (MQTT sensors + relay AC Dry-contact)
mqtt_topic_esp_bathroom_ac_status: custom_route/id_esp8/status
mqtt_topic_esp_bathroom_ac_command: custom_route/id_esp8/command
mqtt_topic_esp_bathroom_ac_lwt: custom_route/id_esp8/lwt
# WROOM32 dormitorio
mqtt_topic_esp_bedroom_status: custom_route/id_esp9/status
mqtt_topic_esp_bedroom_command: custom_route/id_esp9/command
mqtt_topic_esp_bedroom_lwt: custom_route/id_esp9/lwt
# ESP DEV TEST (MQTT sensors)
mqtt_topic_esp_dev1_oled_status: custom_route/id_esp10/status
mqtt_topic_esp_dev1_oled_command: custom_route/id_esp10/command
mqtt_topic_esp_dev1_oled_lwt: custom_route/id_esp10/lwt
# ESP HALL (Light switch mode + light sensor)
mqtt_topic_esp_hall_status: custom_route/id_esp11/status
mqtt_topic_esp_hall_command: custom_route/id_esp11/command
mqtt_topic_esp_hall_lwt: custom_route/id_esp11/lwt

mpd_host: 192.168.200.252
mpd_port: 6610
mopidy_url: https://secret.com/musicbox_webclient/index.html
kodi_user: osmc
kodi_pw: osmc
kodi_host: 192.168.200.251
kodi_port: 8080
kill_kodi_cmd: ssh -l osmc rpi3osmc /home/osmc/PYTHON/killkodi.sh
ssh_cmd_rpi_temp_kodi: ssh osmc@rpi3osmc cat /sys/class/thermal/thermal_zone0/temp
kodi_url: https://secret.com/kodi/

# MotionEye urls
motioneye_url: https://secret.com/cams/
sricam_motioneye_local_snapshot: http://192.168.200.203:8765/picture/1/current/?_username=me&_signature=lalala
sricam_motioneye_command_status: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 1 status'
sricam_motioneye_command_mov_on: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 1 start'
sricam_motioneye_command_mov_off: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 1 pause'
kmoon_motioneye_local_snapshot: http://192.168.200.203:8765/picture/2/current/?_username=me&_signature=lalala
kmoon_motioneye_command_status: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 2 status'
kmoon_motioneye_command_mov_on: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 2 start'
kmoon_motioneye_command_mov_off: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 2 pause'
iegeek_motioneye_local_snapshot: http://192.168.200.203:8765/picture/3/current/?_username=me&_signature=lalala
iegeek_motioneye_command_status: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 3 status'
iegeek_motioneye_command_mov_on: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 3 start'
iegeek_motioneye_command_mov_off: '/config/shell/switch_camera_motion_detection.sh 192.168.200.203 3 pause'
