entities:
# WAN access
  - name: NAS QNAP
    url: !secret weblink_nas_qnap_url
  - name: NAS Synology
    url: !secret weblink_nas_url
#   - name: Grafana
#     url: !secret grafana_url
#   - name: MotionEye
#     url: !secret motioneye_url
#   - name: enerPI
#     url: !secret enerpi_url
  - name: Router Movistar
    url: http://192.168.1.1

  - name: HASSIO LAN
    url: !secret weblink_hassio_lan
  - name: HASSIO PI-Hole
    url: !secret weblink_hassio_pihole
#  - name: HASSIO IDE
#    url: !secret weblink_hassio_ide
  - name: Mopidy
    url: !secret mopidy_url
  - name: TV Headend
    url: !secret weblink_tv_headend
  - name: Kodi web interface
    url: !secret weblink_kodi_web

  - name: Slave HASS
    url: http://192.168.1.46:8123/
  - name: Slave HASS MPD
    url: http://192.168.1.52:8123/
  - name: enerPI
    url: !secret enerpi_url