entities:
# WAN access
  - name: Grafana
    url: !secret grafana_url
  - name: Consumo eléctrico
    url: !secret grafana_elec_url
  - name: NAS QNAP
    url: !secret weblink_nas_qnap_url
  - name: NAS Synology
    url: !secret weblink_nas_url
  - name: Contabilidad
    url: !secret weblink_contab_url
#   - name: MotionEye
#     url: !secret motioneye_url
  - name: Router Movistar
    url: http://192.168.1.1

#  - name: Wifi repeater
#    url: http://192.168.1.54

  - name: HASSIO LAN
    url: !secret weblink_hassio_lan
  - name: PI-Hole
    url: !secret weblink_pihole
#  - name: HASSIO IDE
#    url: !secret weblink_hassio_ide
#  - name: Mopidy
#    url: !secret mopidy_url
  - name: TV Headend
    url: !secret weblink_tv_headend
  - name: Kodi web interface
    url: !secret weblink_kodi_web

#  - name: Slave HASS
#    url: http://192.168.1.46:8123/
#  - name: Slave HASS MPD
#    url: http://192.168.1.52:8123/
  - name: MotionEye
    url: !secret motioneye_url

# Custom SaaS
  - name: Buscador de torrents
    url: !secret url_saas_torrent_search