entities:
# WAN access
  - name: NAS QNAP
    url: !secret weblink_nas_qnap_url
  - name: NAS Synology
    url: !secret weblink_nas_url
#   - name: Grafana
#     url: !secret grafana_url
#   - name: MotionEye
#     url: !secret motioneye_url
#   - name: enerPI
#     url: !secret enerpi_url

# LAN-Only access
  - name: HASSIO LAN
    url: !secret weblink_hassio_lan
  - name: HASSIO PI-Hole
    url: !secret weblink_hassio_pihole
  - name: HASSIO IDE
    url: !secret weblink_hassio_ide
#   - name: Mopidy
#     url: !secret mopidy_url
#   - name: Slave HASS
#     url: http://192.168.1.46:8123/
#   - name: Slave HASS MPD
#     url: http://192.168.1.52:8123/
#  - name: enerPI 2x
#    url: http://192.168.1.52/enerpi/
#  - name: PyOutlets
#    url: http://192.168.1.13/outlets
#   - name: Router Interfibra
#     url: http://192.168.1.1
#   - name: Wifi Extender AP
#     url: http://192.168.1.11

  - name: TV Headend
    url: !secret weblink_tv_headend
  - name: Kodi web interface
    url: !secret weblink_kodi_web
#   - name: Contabilidad
#     url: !secret weblink_contab_url